import { TemaConocimiento } from "./conocimiento";

// Segundo bloque de la base de conocimiento: filosofía de negocio y
// las ideas de los libros que más circulan entre emprendedores
// (Padre Rico Padre Pobre, Las 48 Leyes del Poder), más el terreno de
// la llamada "psicología oscura".
//
// Va aparte de conocimiento.ts solo por tamaño: el motor de detección
// los junta y los trata igual. Misma regla de tipos, así que
// TypeScript sigue exigiendo los 7 idiomas por tema.
//
// Criterio con estos temas: se explican las ideas de verdad, sin
// adornarlas, incluyendo las críticas que reciben — repetir un libro
// como si fuera evangelio no le sirve a nadie que esté arriesgando su
// dinero. Y en lo que toca a manipulación, el enfoque es reconocerla
// cuando te la aplican a ti, que es donde de verdad le sirve a alguien
// que atiende un negocio.
export const TEMAS_FILOSOFIA: TemaConocimiento[] = [
  // ---------------------------------------------------------------
  // PADRE RICO, PADRE POBRE
  // ---------------------------------------------------------------
  {
    id: "activos_pasivos",
    palabras: [
      "activo", "activos", "pasivo", "pasivos", "activos y pasivos",
      "padre rico", "padre rico padre pobre", "kiyosaki", "rich dad",
      "diferencia entre activo y pasivo", "que es un activo", "ativos e passivos",
      "actif et passif", "vermogenswert", "attivo e passivo", "资产和负债",
    ],
    respuesta: {
      es: "La idea central de **Padre Rico, Padre Pobre** es una definición muy simple:\n\n**Activo = te mete dinero al bolsillo. Pasivo = te lo saca.**\n\nUn local que rentas es activo. Un local que pagas y no usas es pasivo. Tu inventario que rota es activo; el que lleva ocho meses parado es pasivo disfrazado de activo, porque te cuesta espacio y dinero congelado.\n\nEl consejo práctico que sale de ahí: **compra primero cosas que produzcan dinero y deja que ellas te paguen los lujos.** La mayoría hace lo contrario — primero la camioneta, después a ver cómo la paga.\n\nSé justo con el libro: es bueno para cambiarte el chip sobre en qué gastas, pero es muy vago en el cómo, sus definiciones no son las contables, y el propio autor ha tenido resultados discutibles. Tómalo como una forma de pensar, no como un manual.",
      en: "The central idea of **Rich Dad, Poor Dad** is a very simple definition:\n\n**An asset puts money in your pocket. A liability takes it out.**\n\nA shop you rent out is an asset. A shop you pay for and don't use is a liability. Inventory that turns over is an asset; inventory sitting for eight months is a liability disguised as an asset, because it costs you space and frozen cash.\n\nThe practical advice that follows: **buy things that produce money first, and let them pay for your luxuries.** Most people do the opposite — the truck first, then figure out how to pay for it.\n\nBe fair to the book: it's good for changing how you think about spending, but it's very vague on the how, its definitions aren't the accounting ones, and the author's own results are debatable. Take it as a way of thinking, not a manual.",
      pt: "A ideia central de **Pai Rico, Pai Pobre** é uma definição bem simples:\n\n**Ativo = coloca dinheiro no seu bolso. Passivo = tira.**\n\nUm ponto que você aluga é ativo. Um ponto que você paga e não usa é passivo. Seu estoque que gira é ativo; o que está parado há oito meses é passivo disfarçado de ativo, porque custa espaço e dinheiro congelado.\n\nO conselho prático que sai daí: **compre primeiro coisas que produzam dinheiro e deixe que elas paguem seus luxos.** A maioria faz o contrário — primeiro a caminhonete, depois vê como paga.\n\nSeja justo com o livro: é bom para mudar a cabeça sobre onde você gasta, mas é muito vago no como, suas definições não são as contábeis, e o próprio autor teve resultados discutíveis. Pegue como forma de pensar, não como manual.",
      fr: "L'idée centrale de **Père riche, père pauvre** est une définition très simple :\n\n**Un actif met de l'argent dans votre poche. Un passif en sort.**\n\nUn local que vous louez est un actif. Un local que vous payez sans l'utiliser est un passif. Un stock qui tourne est un actif ; un stock immobile depuis huit mois est un passif déguisé en actif, car il vous coûte de la place et de la trésorerie gelée.\n\nLe conseil pratique qui en découle : **achetez d'abord ce qui produit de l'argent, et laissez-le payer vos luxes.** La plupart font l'inverse — d'abord la camionnette, ensuite on verra comment la payer.\n\nSoyez juste avec le livre : il est utile pour changer votre regard sur la dépense, mais très vague sur le comment, ses définitions ne sont pas celles de la comptabilité, et les résultats de l'auteur lui-même sont discutables. Prenez-le comme une façon de penser, pas comme un manuel.",
      de: "Die Kernidee von **Rich Dad, Poor Dad** ist eine sehr einfache Definition:\n\n**Ein Vermögenswert bringt Geld in deine Tasche. Eine Verbindlichkeit holt es heraus.**\n\nEin Laden, den du vermietest, ist ein Vermögenswert. Ein Laden, den du zahlst und nicht nutzt, ist eine Verbindlichkeit. Ware, die sich dreht, ist ein Vermögenswert; Ware, die seit acht Monaten steht, ist eine als Vermögenswert verkleidete Verbindlichkeit, denn sie kostet Platz und eingefrorenes Geld.\n\nDer praktische Rat daraus: **Kauf zuerst Dinge, die Geld erzeugen, und lass sie deine Annehmlichkeiten bezahlen.** Die meisten machen es umgekehrt — erst der Pick-up, dann sehen wir weiter.\n\nSei fair zum Buch: Es hilft, das Denken über Ausgaben zu ändern, ist aber sehr vage beim Wie, seine Definitionen sind nicht die der Buchhaltung, und die Ergebnisse des Autors selbst sind umstritten. Nimm es als Denkweise, nicht als Handbuch.",
      zh: "**《富爸爸穷爸爸》**的核心思想是一个非常简单的定义：\n\n**资产 = 把钱放进你口袋。负债 = 把钱从你口袋拿走。**\n\n你租出去的铺面是资产。你付着租金却不用的铺面是负债。周转的库存是资产；压了八个月的库存是伪装成资产的负债，因为它占地方、冻结资金。\n\n由此得出的实用建议：**先买能生钱的东西，让它们来付你的享受。** 大多数人反着来——先买车，再想怎么还。\n\n也要公道地看这本书：它能改变你对花钱的思维，但在「怎么做」上非常笼统，它的定义并非会计意义上的定义，作者本人的实际成绩也有争议。把它当成一种思维方式，而不是操作手册。",
      it: "L'idea centrale di **Padre ricco, padre povero** è una definizione molto semplice:\n\n**Attivo = ti mette soldi in tasca. Passivo = te li toglie.**\n\nUn locale che affitti è un attivo. Un locale che paghi e non usi è un passivo. Il magazzino che ruota è un attivo; quello fermo da otto mesi è un passivo travestito da attivo, perché ti costa spazio e denaro congelato.\n\nIl consiglio pratico che ne deriva: **compra prima le cose che producono denaro e lascia che siano loro a pagarti i lussi.** La maggioranza fa il contrario — prima il furgone, poi si vedrà come pagarlo.\n\nSii onesto con il libro: è utile per cambiare il modo in cui pensi alla spesa, ma è molto vago sul come, le sue definizioni non sono quelle contabili, e i risultati dell'autore stesso sono discutibili. Prendilo come un modo di pensare, non come un manuale.",
    },
  },
  {
    id: "cuadrante_flujo",
    palabras: [
      "cuadrante", "cuadrante del flujo", "cuadrante del dinero", "empleado autoempleado",
      "dueno de negocio inversionista", "cashflow quadrant", "quadrante",
      "quadrant", "四象限",
    ],
    respuesta: {
      es: "El **cuadrante del flujo de dinero** divide de dónde viene el ingreso de alguien en cuatro casillas:\n\n**E — Empleado:** cambias tiempo por sueldo.\n**A — Autoempleado:** eres tu propio jefe, pero si tú no estás, no se factura. Muchos dueños de negocio están aquí sin saberlo.\n**D — Dueño de negocio:** tienes un sistema y gente que opera sin ti.\n**I — Inversionista:** tu dinero trabaja.\n\nLa pregunta incómoda: **si te enfermas dos semanas, ¿tu negocio factura?** Si la respuesta es no, tienes un empleo que además te quita el sueño, no un negocio.\n\nEl salto de A a D no es tener más ventas: es documentar cómo se hace cada cosa, entrenar a alguien, y aguantar que al principio lo haga peor que tú. Ese es el precio real, y por eso casi nadie lo cruza.",
      en: "The **cashflow quadrant** splits where someone's income comes from into four boxes:\n\n**E — Employee:** you trade time for a salary.\n**S — Self-employed:** you're your own boss, but if you're not there, nothing gets billed. Many business owners are here without realising it.\n**B — Business owner:** you have a system and people who run it without you.\n**I — Investor:** your money works.\n\nThe uncomfortable question: **if you're sick for two weeks, does your business still bill?** If the answer is no, you have a job that also costs you sleep, not a business.\n\nThe jump from S to B isn't more sales: it's documenting how each thing gets done, training someone, and tolerating that at first they'll do it worse than you. That's the real price, and it's why almost nobody crosses it.",
      pt: "O **quadrante do fluxo de dinheiro** divide de onde vem a renda de alguém em quatro caixas:\n\n**E — Empregado:** troca tempo por salário.\n**A — Autônomo:** é seu próprio chefe, mas se você não está, não se fatura. Muitos donos de negócio estão aqui sem saber.\n**D — Dono de negócio:** tem um sistema e gente que opera sem você.\n**I — Investidor:** seu dinheiro trabalha.\n\nA pergunta incômoda: **se você adoecer duas semanas, seu negócio fatura?** Se a resposta é não, você tem um emprego que ainda te tira o sono, não um negócio.\n\nO salto de A para D não é ter mais vendas: é documentar como se faz cada coisa, treinar alguém, e aguentar que no início faça pior que você. Esse é o preço real, e por isso quase ninguém atravessa.",
      fr: "Le **quadrant du cashflow** répartit l'origine des revenus en quatre cases :\n\n**E — Employé :** vous échangez du temps contre un salaire.\n**T — Travailleur indépendant :** vous êtes votre patron, mais si vous n'êtes pas là, rien n'est facturé. Beaucoup de patrons sont ici sans le savoir.\n**P — Propriétaire d'entreprise :** vous avez un système et des gens qui l'exploitent sans vous.\n**I — Investisseur :** votre argent travaille.\n\nLa question qui dérange : **si vous êtes malade deux semaines, votre entreprise facture-t-elle ?** Si non, vous avez un emploi qui vous empêche de dormir, pas une entreprise.\n\nLe passage de T à P n'est pas plus de ventes : c'est documenter comment chaque chose se fait, former quelqu'un, et accepter qu'au début il le fasse moins bien que vous. C'est le vrai prix, et c'est pourquoi presque personne ne le franchit.",
      de: "Das **Cashflow-Quadrant** teilt die Herkunft von Einkommen in vier Felder:\n\n**E — Angestellter:** Du tauschst Zeit gegen Gehalt.\n**S — Selbstständiger:** Du bist dein eigener Chef, aber wenn du nicht da bist, wird nichts abgerechnet. Viele Inhaber stehen hier, ohne es zu merken.\n**B — Unternehmer:** Du hast ein System und Leute, die es ohne dich betreiben.\n**I — Investor:** Dein Geld arbeitet.\n\nDie unbequeme Frage: **Wenn du zwei Wochen krank bist, rechnet dein Betrieb weiter ab?** Wenn nein, hast du einen Job, der dich obendrein den Schlaf kostet — kein Unternehmen.\n\nDer Sprung von S nach B bedeutet nicht mehr Umsatz: Es heißt, festzuhalten, wie jede Sache gemacht wird, jemanden einzuarbeiten und auszuhalten, dass er es anfangs schlechter macht als du. Das ist der wahre Preis, und deshalb schafft ihn fast niemand.",
      zh: "**现金流四象限**把收入来源分成四格：\n\n**E — 雇员：** 用时间换工资。\n**S — 自雇者：** 你是自己的老板，但你不在就没有收入。很多店主其实在这一格却不自知。\n**B — 企业主：** 你有一套系统和替你运转的人。\n**I — 投资者：** 你的钱在工作。\n\n那个扎心的问题：**如果你病倒两周，你的生意还有收入吗？** 如果答案是没有，那你拥有的是一份还让你睡不着觉的工作，而不是一门生意。\n\n从 S 跨到 B，靠的不是更多销量：而是把每件事怎么做写下来、培养人、并且忍受他一开始做得没你好。这才是真正的代价，也是几乎没人跨过去的原因。",
      it: "Il **quadrante del cashflow** divide da dove arriva il reddito di qualcuno in quattro caselle:\n\n**D — Dipendente:** scambi tempo per stipendio.\n**A — Autonomo:** sei il capo di te stesso, ma se non ci sei tu non si fattura. Molti titolari sono qui senza saperlo.\n**T — Titolare d'impresa:** hai un sistema e persone che lo fanno funzionare senza di te.\n**I — Investitore:** i tuoi soldi lavorano.\n\nLa domanda scomoda: **se stai male due settimane, la tua attività fattura?** Se la risposta è no, hai un lavoro che per giunta ti toglie il sonno, non un'impresa.\n\nIl salto da A a T non sono più vendite: è documentare come si fa ogni cosa, formare qualcuno e sopportare che all'inizio lo faccia peggio di te. Quello è il prezzo vero, ed è per questo che quasi nessuno lo attraversa.",
    },
  },
  {
    id: "educacion_financiera",
    palabras: [
      "educacion financiera", "los ricos no trabajan por dinero", "mentalidad de rico",
      "mentalidad financiera", "libertad financiera", "ingresos pasivos",
      "financial literacy", "passive income", "liberdade financeira",
      "liberte financiere", "finanzielle bildung", "liberta finanziaria", "财务自由",
    ],
    respuesta: {
      es: "La tesis de fondo: **la escuela enseña a trabajar por dinero, no a que el dinero trabaje.** Y hay algo de verdad — casi nadie sale sabiendo leer un estado de resultados o calcular un interés real.\n\nLo aprovechable para alguien que ya tiene un negocio:\n\n• **Aprende a leer tus propios números.** No necesitas un diplomado: margen, punto de equilibrio, flujo de caja y rotación. Con eso decides mejor que la mayoría.\n• **Págate primero.** Aparta un porcentaje fijo en cuanto entra el dinero, antes de gastar. Si esperas a que \"sobre\", nunca sobra.\n• **Compra el activo antes que el lujo.** La camioneta después de que el negocio la pague, no antes.\n\nY una advertencia honesta: **\"ingreso pasivo\" casi nunca es pasivo.** Un local rentado, un negocio con encargado o una inversión requieren vigilancia. Quien te vende ingresos sin trabajo normalmente está vendiendo el curso, no el resultado. Desconfía de todo el que gane más enseñando a ganar dinero que haciéndolo.",
      en: "The underlying thesis: **school teaches you to work for money, not to make money work.** And there's something to it — almost nobody leaves school able to read an income statement or work out a real interest rate.\n\nWhat's usable for someone who already has a business:\n\n• **Learn to read your own numbers.** You don't need a degree: margin, break-even, cash flow and turnover. With those you decide better than most.\n• **Pay yourself first.** Set aside a fixed percentage as soon as money comes in, before spending. If you wait for what's \"left over\", nothing is ever left over.\n• **Buy the asset before the luxury.** The truck after the business pays for it, not before.\n\nAnd an honest warning: **\"passive income\" is almost never passive.** A rented-out unit, a business with a manager, or an investment all need watching. Whoever sells you income without work is usually selling the course, not the result. Be suspicious of anyone who earns more teaching how to make money than making it.",
      pt: "A tese de fundo: **a escola ensina a trabalhar por dinheiro, não a fazer o dinheiro trabalhar.** E há verdade nisso — quase ninguém sai sabendo ler um demonstrativo de resultados ou calcular juros reais.\n\nO aproveitável para quem já tem um negócio:\n\n• **Aprenda a ler seus próprios números.** Não precisa de curso: margem, ponto de equilíbrio, fluxo de caixa e giro. Com isso você decide melhor que a maioria.\n• **Pague-se primeiro.** Separe uma porcentagem fixa assim que o dinheiro entra, antes de gastar. Se esperar o que \"sobrar\", nunca sobra.\n• **Compre o ativo antes do luxo.** A caminhonete depois que o negócio a pagar, não antes.\n\nE um aviso honesto: **\"renda passiva\" quase nunca é passiva.** Um ponto alugado, um negócio com gerente ou um investimento exigem vigilância. Quem te vende renda sem trabalho normalmente está vendendo o curso, não o resultado. Desconfie de quem ganha mais ensinando a ganhar dinheiro do que ganhando.",
      fr: "La thèse de fond : **l'école apprend à travailler pour l'argent, pas à faire travailler l'argent.** Et il y a du vrai — presque personne n'en sort capable de lire un compte de résultat ou de calculer un taux réel.\n\nCe qui est exploitable pour qui a déjà une entreprise :\n\n• **Apprenez à lire vos propres chiffres.** Pas besoin de diplôme : marge, seuil de rentabilité, trésorerie et rotation. Avec ça, vous décidez mieux que la plupart.\n• **Payez-vous d'abord.** Mettez de côté un pourcentage fixe dès l'encaissement, avant de dépenser. Si vous attendez ce qui « reste », il ne reste jamais rien.\n• **Achetez l'actif avant le luxe.** La camionnette après que l'entreprise l'ait payée, pas avant.\n\nEt un avertissement honnête : **le « revenu passif » n'est presque jamais passif.** Un local loué, une entreprise avec un gérant ou un placement demandent de la surveillance. Celui qui vous vend du revenu sans travail vend en général la formation, pas le résultat. Méfiez-vous de qui gagne plus à enseigner comment gagner de l'argent qu'à en gagner.",
      de: "Die Grundthese: **Die Schule lehrt, für Geld zu arbeiten, nicht Geld arbeiten zu lassen.** Und da ist etwas dran — kaum jemand verlässt sie und kann eine Gewinn-und-Verlust-Rechnung lesen oder einen realen Zins berechnen.\n\nWas für jemanden mit bestehendem Betrieb brauchbar ist:\n\n• **Lerne, deine eigenen Zahlen zu lesen.** Du brauchst kein Studium: Marge, Gewinnschwelle, Cashflow und Umschlag. Damit entscheidest du besser als die meisten.\n• **Zahl dich zuerst.** Leg einen festen Prozentsatz zurück, sobald Geld hereinkommt, vor dem Ausgeben. Wartest du auf das, was „übrig bleibt\", bleibt nie etwas übrig.\n• **Kauf den Vermögenswert vor dem Luxus.** Den Pick-up, nachdem der Betrieb ihn bezahlt hat, nicht vorher.\n\nUnd eine ehrliche Warnung: **„Passives Einkommen\" ist fast nie passiv.** Ein vermietetes Objekt, ein Betrieb mit Geschäftsführer oder eine Anlage brauchen Aufsicht. Wer dir Einkommen ohne Arbeit verkauft, verkauft meist den Kurs, nicht das Ergebnis. Sei misstrauisch bei jedem, der mehr damit verdient, Geldverdienen zu lehren, als damit, Geld zu verdienen.",
      zh: "核心论点：**学校教你为钱工作，而不是让钱为你工作。** 这话有几分道理——几乎没人毕业时会看利润表或算实际利率。\n\n对已经有生意的人，能用得上的是：\n\n• **学会看懂自己的数字。** 不需要文凭：利润率、盈亏平衡点、现金流、周转率。掌握这几个，你的决策就胜过大多数人。\n• **先付给自己。** 钱一进来就先按固定比例存起来，再谈花钱。等「有剩的」，永远不会有剩的。\n• **先买资产，再买享受。** 等生意付得起了再买车，不是提前买。\n\n还有一句实话：**「被动收入」几乎从来不是被动的。** 出租的铺面、交给店长的生意、一笔投资，都需要盯着。那些卖你「不劳而获收入」的人，通常卖的是课程，不是结果。凡是靠教人赚钱赚得比自己做生意还多的人，都值得怀疑。",
      it: "La tesi di fondo: **la scuola insegna a lavorare per il denaro, non a far lavorare il denaro.** E qualcosa di vero c'è — quasi nessuno ne esce sapendo leggere un conto economico o calcolare un interesse reale.\n\nCosa è utilizzabile per chi ha già un'attività:\n\n• **Impara a leggere i tuoi numeri.** Non serve un titolo: margine, punto di pareggio, flusso di cassa e rotazione. Con quelli decidi meglio della maggioranza.\n• **Pagati per primo.** Metti da parte una percentuale fissa appena entra il denaro, prima di spendere. Se aspetti quello che \"avanza\", non avanza mai.\n• **Compra l'attivo prima del lusso.** Il furgone dopo che l'attività lo ha pagato, non prima.\n\nE un avvertimento onesto: **il \"reddito passivo\" non è quasi mai passivo.** Un locale affittato, un'attività con un responsabile o un investimento richiedono sorveglianza. Chi ti vende reddito senza lavoro di solito sta vendendo il corso, non il risultato. Diffida di chi guadagna più insegnando a fare soldi che facendoli.",
    },
  },

  // ---------------------------------------------------------------
  // LAS 48 LEYES DEL PODER
  // ---------------------------------------------------------------
  {
    id: "leyes_poder",
    palabras: [
      "48 leyes del poder", "leyes del poder", "las 48 leyes", "robert greene",
      "48 laws of power", "leis do poder", "lois du pouvoir", "gesetze der macht",
      "leggi del potere", "权力的48条法则",
    ],
    respuesta: {
      es: "**Las 48 Leyes del Poder** de Robert Greene es un catálogo de cómo se ha ejercido el poder históricamente — cortes, guerras, política. No es un libro de moral: describe lo que funciona, no lo que está bien.\n\nLas que de verdad sirven en un negocio:\n\n• **Nunca eclipses al superior.** Tu proveedor grande, tu casero, tu cliente institucional: no los hagas sentir menos aunque tengas razón.\n• **Cuida tu reputación como si fuera tu vida.** En un negocio local es literalmente tu activo más caro y el más difícil de reconstruir.\n• **Haz que la gente venga a ti.** Quien persigue, pierde poder de negociación. Aplica igual con clientes que con proveedores.\n• **Di menos de lo necesario.** En una negociación, el que habla de más entrega información gratis.\n• **Consigue que otros hagan el trabajo, pero llévate el crédito** — esta úsala al revés: dale el crédito a tu gente y te seguirán años.\n\nMi lectura honesta: úsalo como **manual de defensa**. Sirve muchísimo para reconocer a quien te está aplicando estas tácticas. Como manual de ataque en un negocio chico, donde todos se conocen y la reputación lo es todo, la mayoría te sale carísimo. Pregúntame por \"leyes peligrosas\" si quieres el detalle.",
      en: "**The 48 Laws of Power** by Robert Greene is a catalogue of how power has historically been exercised — courts, wars, politics. It's not a book about morality: it describes what works, not what's right.\n\nThe ones that genuinely help in business:\n\n• **Never outshine the master.** Your big supplier, your landlord, your institutional client: don't make them feel small even when you're right.\n• **Guard your reputation with your life.** In a local business it's literally your most expensive asset and the hardest to rebuild.\n• **Make people come to you.** Whoever chases loses negotiating power. Applies to customers and suppliers alike.\n• **Say less than necessary.** In a negotiation, whoever talks too much gives away information for free.\n• **Get others to do the work, but take the credit** — use this one in reverse: give your people the credit and they'll stay with you for years.\n\nMy honest reading: use it as a **defence manual**. It's enormously useful for recognising when someone is running these tactics on you. As an attack manual in a small business, where everyone knows everyone and reputation is everything, most of them cost you dearly. Ask me about \"dangerous laws\" if you want the detail.",
      pt: "**As 48 Leis do Poder**, de Robert Greene, é um catálogo de como o poder foi exercido historicamente — cortes, guerras, política. Não é um livro de moral: descreve o que funciona, não o que é certo.\n\nAs que realmente servem num negócio:\n\n• **Nunca ofusque o superior.** Seu fornecedor grande, seu locador, seu cliente institucional: não os faça se sentirem menores mesmo quando você tem razão.\n• **Cuide da sua reputação como da própria vida.** Num negócio local é literalmente seu ativo mais caro e o mais difícil de reconstruir.\n• **Faça as pessoas virem até você.** Quem persegue perde poder de negociação. Vale para clientes e fornecedores.\n• **Diga menos que o necessário.** Numa negociação, quem fala demais entrega informação de graça.\n• **Faça outros trabalharem, mas leve o crédito** — use ao contrário: dê o crédito à sua gente e eles ficarão anos.\n\nMinha leitura honesta: use como **manual de defesa**. Serve muitíssimo para reconhecer quem está aplicando essas táticas em você. Como manual de ataque num negócio pequeno, onde todos se conhecem e a reputação é tudo, a maioria sai caríssima. Pergunte por \"leis perigosas\" se quiser o detalhe.",
      fr: "**Les 48 lois du pouvoir** de Robert Greene est un catalogue de la façon dont le pouvoir s'est exercé historiquement — cours, guerres, politique. Ce n'est pas un livre de morale : il décrit ce qui marche, pas ce qui est juste.\n\nCelles qui servent vraiment en affaires :\n\n• **N'éclipsez jamais le maître.** Votre gros fournisseur, votre bailleur, votre client institutionnel : ne les rabaissez pas, même quand vous avez raison.\n• **Protégez votre réputation comme votre vie.** Dans un commerce local, c'est littéralement votre actif le plus cher et le plus dur à reconstruire.\n• **Faites venir les gens à vous.** Qui court perd du pouvoir de négociation. Vaut pour les clients comme pour les fournisseurs.\n• **Dites-en moins que nécessaire.** En négociation, celui qui parle trop donne de l'information gratuitement.\n• **Faites travailler les autres et prenez le crédit** — utilisez celle-ci à l'envers : donnez le crédit à vos gens et ils resteront des années.\n\nMa lecture honnête : servez-vous-en comme **manuel de défense**. C'est extrêmement utile pour repérer qui vous applique ces tactiques. Comme manuel d'attaque dans une petite entreprise, où tout le monde se connaît et où la réputation fait tout, la plupart vous coûtent très cher. Demandez-moi les « lois dangereuses » pour le détail.",
      de: "**Die 48 Gesetze der Macht** von Robert Greene ist ein Katalog dessen, wie Macht historisch ausgeübt wurde — Höfe, Kriege, Politik. Es ist kein Moralbuch: Es beschreibt, was funktioniert, nicht was richtig ist.\n\nDie, die im Geschäft wirklich helfen:\n\n• **Stelle den Meister nie in den Schatten.** Deinen großen Lieferanten, deinen Vermieter, deinen institutionellen Kunden: Lass sie sich nicht klein fühlen, auch wenn du recht hast.\n• **Hüte deinen Ruf wie dein Leben.** In einem lokalen Betrieb ist er buchstäblich dein teuerster Vermögenswert und der am schwersten wiederaufzubauende.\n• **Lass die Leute zu dir kommen.** Wer hinterherläuft, verliert Verhandlungsmacht. Gilt für Kunden wie für Lieferanten.\n• **Sag weniger als nötig.** In einer Verhandlung verschenkt derjenige Informationen, der zu viel redet.\n• **Lass andere die Arbeit tun, nimm aber den Ruhm** — nutze dieses umgekehrt: Gib deinen Leuten den Ruhm, und sie bleiben jahrelang.\n\nMeine ehrliche Lesart: Nutze es als **Verteidigungshandbuch**. Es hilft enorm zu erkennen, wenn jemand diese Taktiken bei dir anwendet. Als Angriffshandbuch in einem kleinen Betrieb, wo jeder jeden kennt und der Ruf alles ist, kommen dich die meisten teuer zu stehen. Frag mich nach „gefährlichen Gesetzen\", wenn du Details willst.",
      zh: "罗伯特·格林的**《权力的48条法则》**是一部关于历史上权力如何被行使的目录——宫廷、战争、政治。它不是一本讲道德的书：它描述什么管用，而不是什么正确。\n\n在生意上真正有用的几条：\n\n• **永远不要盖过上位者的风头。** 你的大供应商、房东、机构客户：即使你有理，也别让他们觉得矮了一截。\n• **像守护生命一样守护名声。** 在本地生意里，名声就是你最贵、最难重建的资产。\n• **让别人主动来找你。** 追着跑的一方会失去议价能力。对客户和供应商都适用。\n• **少说话。** 谈判中话多的一方在免费送出信息。\n• **让别人干活，自己拿功劳**——这条要反着用：把功劳给你的人，他们会跟你干很多年。\n\n我的实话：把它当作**防守手册**。用来识别谁在对你施展这些手段，非常管用。而在人人相识、名声就是一切的小生意里，把它当进攻手册用，多数法则的代价都极其昂贵。想了解细节可以问我「危险的法则」。",
      it: "**Le 48 leggi del potere** di Robert Greene è un catalogo di come il potere è stato esercitato storicamente — corti, guerre, politica. Non è un libro di morale: descrive ciò che funziona, non ciò che è giusto.\n\nQuelle che servono davvero in un'attività:\n\n• **Non mettere mai in ombra il superiore.** Il tuo grande fornitore, il proprietario del locale, il cliente istituzionale: non farli sentire piccoli nemmeno quando hai ragione.\n• **Custodisci la reputazione come la vita.** In un'attività locale è letteralmente il tuo bene più costoso e il più difficile da ricostruire.\n• **Fa' che siano gli altri a venire da te.** Chi insegue perde potere negoziale. Vale con i clienti come con i fornitori.\n• **Di' meno del necessario.** In una trattativa, chi parla troppo regala informazioni.\n• **Fa' lavorare gli altri, ma prenditi il merito** — usa questa al contrario: dai il merito alla tua gente e ti resteranno accanto per anni.\n\nLa mia lettura onesta: usalo come **manuale di difesa**. È utilissimo per riconoscere chi sta applicando queste tattiche a te. Come manuale d'attacco in una piccola attività, dove tutti si conoscono e la reputazione è tutto, la maggior parte ti costa carissimo. Chiedimi delle \"leggi pericolose\" se vuoi il dettaglio.",
    },
  },
  {
    id: "leyes_peligrosas",
    palabras: [
      "leyes peligrosas", "leyes del poder son peligrosas", "leyes que no debo usar", "cuales leyes evitar", "aplastar al enemigo",
      "manipular socios", "traicionar", "cuales leyes son malas",
      "dangerous laws", "leis perigosas", "lois dangereuses", "gefahrliche gesetze",
      "leggi pericolose", "危险的法则",
    ],
    respuesta: {
      es: "De las 48 leyes, varias funcionan en una corte del siglo XVI y te destruyen en un negocio de barrio. Estas son las que yo no aplicaría:\n\n• **\"Aplasta por completo a tu enemigo\".** En un mercado local, el competidor de hoy es el que te presta mercancía cuando te quedas sin stock. Nadie olvida una humillación.\n• **\"Usa la rendición como herramienta de poder\" / fingir debilidad.** Con proveedores y bancos, la fama de poco confiable te cierra el crédito años.\n• **\"Que otros hagan el trabajo y llévate el crédito\".** Es la forma más rápida de perder al empleado bueno, que en un negocio chico vale más que cualquier táctica.\n• **\"Juega con la necesidad de creer de la gente\".** Eso es engañar clientes. Funciona una vez y te cuesta el negocio.\n\n**La razón de fondo:** esas leyes se escribieron para entornos donde los jugadores cambian y nadie se vuelve a ver. Un negocio local es lo contrario: **juego repetido, con las mismas personas, por años.** En juegos repetidos, la reputación vence a la astucia casi siempre — y el que hace trampa se queda sin con quién jugar.\n\nQuédate con la parte de leer intenciones y proteger tu posición. Esa sí te sirve todos los días.",
      en: "Of the 48 laws, several work in a 16th-century court and destroy you in a neighbourhood business. These are the ones I wouldn't apply:\n\n• **\"Crush your enemy totally\".** In a local market, today's competitor is the one who lends you goods when you run out of stock. Nobody forgets a humiliation.\n• **\"Use surrender as a tool of power\" / feigning weakness.** With suppliers and banks, a reputation for unreliability shuts your credit down for years.\n• **\"Get others to do the work and take the credit\".** It's the fastest way to lose the good employee, who in a small business is worth more than any tactic.\n• **\"Play on people's need to believe\".** That's deceiving customers. It works once and costs you the business.\n\n**The underlying reason:** those laws were written for settings where the players change and nobody meets again. A local business is the opposite: **a repeated game, with the same people, for years.** In repeated games reputation beats cunning almost every time — and the cheat runs out of people willing to play.\n\nKeep the part about reading intentions and protecting your position. That one serves you every day.",
      pt: "Das 48 leis, várias funcionam numa corte do século XVI e te destroem num negócio de bairro. Estas são as que eu não aplicaria:\n\n• **\"Esmague completamente seu inimigo\".** Num mercado local, o concorrente de hoje é quem te empresta mercadoria quando você fica sem estoque. Ninguém esquece uma humilhação.\n• **\"Use a rendição como ferramenta de poder\" / fingir fraqueza.** Com fornecedores e bancos, a fama de pouco confiável fecha seu crédito por anos.\n• **\"Faça outros trabalharem e leve o crédito\".** É o jeito mais rápido de perder o bom funcionário, que num negócio pequeno vale mais que qualquer tática.\n• **\"Jogue com a necessidade das pessoas de acreditar\".** Isso é enganar clientes. Funciona uma vez e custa o negócio.\n\n**A razão de fundo:** essas leis foram escritas para ambientes onde os jogadores mudam e ninguém se vê de novo. Um negócio local é o contrário: **jogo repetido, com as mesmas pessoas, por anos.** Em jogos repetidos, a reputação vence a astúcia quase sempre — e quem trapaceia fica sem com quem jogar.\n\nFique com a parte de ler intenções e proteger sua posição. Essa sim serve todos os dias.",
      fr: "Sur les 48 lois, plusieurs fonctionnent dans une cour du XVIᵉ siècle et vous détruisent dans un commerce de quartier. Voici celles que je n'appliquerais pas :\n\n• **« Écrasez totalement votre ennemi ».** Sur un marché local, le concurrent d'aujourd'hui est celui qui vous dépanne en marchandise quand vous êtes en rupture. Personne n'oublie une humiliation.\n• **« Utilisez la reddition comme arme » / feindre la faiblesse.** Avec fournisseurs et banques, une réputation de peu fiable vous ferme le crédit pour des années.\n• **« Faites travailler les autres et prenez le crédit ».** C'est le plus court chemin pour perdre le bon employé, qui dans une petite entreprise vaut plus que n'importe quelle tactique.\n• **« Jouez sur le besoin de croire des gens ».** C'est tromper les clients. Ça marche une fois et ça coûte l'entreprise.\n\n**La raison de fond :** ces lois ont été écrites pour des milieux où les joueurs changent et ne se revoient jamais. Un commerce local, c'est l'inverse : **un jeu répété, avec les mêmes personnes, pendant des années.** Dans les jeux répétés, la réputation bat la ruse presque toujours — et le tricheur finit sans partenaires.\n\nGardez la partie sur la lecture des intentions et la protection de votre position. Celle-là sert tous les jours.",
      de: "Von den 48 Gesetzen funktionieren einige an einem Hof des 16. Jahrhunderts und zerstören dich im Viertelladen. Diese würde ich nicht anwenden:\n\n• **„Zerschmettere deinen Feind vollständig\".** Im lokalen Markt ist der Konkurrent von heute derjenige, der dir Ware leiht, wenn dir der Bestand ausgeht. Eine Demütigung vergisst niemand.\n• **„Nutze Kapitulation als Machtinstrument\" / Schwäche vortäuschen.** Bei Lieferanten und Banken sperrt dir der Ruf der Unzuverlässigkeit für Jahre den Kredit.\n• **„Lass andere die Arbeit tun und nimm den Ruhm\".** Der schnellste Weg, den guten Mitarbeiter zu verlieren, der in einem kleinen Betrieb mehr wert ist als jede Taktik.\n• **„Spiele mit dem Bedürfnis der Leute zu glauben\".** Das heißt, Kunden zu täuschen. Es funktioniert einmal und kostet dich den Betrieb.\n\n**Der Grund dahinter:** Diese Gesetze wurden für Umgebungen geschrieben, in denen die Spieler wechseln und man sich nie wiedersieht. Ein lokales Geschäft ist das Gegenteil: **ein wiederholtes Spiel, mit denselben Leuten, über Jahre.** In wiederholten Spielen schlägt Ruf die List fast immer — und dem Betrüger gehen die Mitspieler aus.\n\nBehalte den Teil über das Lesen von Absichten und das Schützen deiner Position. Der nützt dir täglich.",
      zh: "48 条法则里，有几条在 16 世纪的宫廷管用，在街坊生意里却会毁了你。这几条我不会用：\n\n• **「彻底打垮你的敌人」。** 在本地市场，今天的竞争对手，就是你断货时借货给你的人。羞辱这种事没人会忘。\n• **「以投降作为权力工具」/ 假装示弱。** 在供应商和银行那里，「不可靠」的名声会让你几年借不到钱。\n• **「让别人干活，自己拿功劳」。** 这是失去好员工最快的方式——在小生意里，一个好员工比任何手段都值钱。\n• **「利用人们想相信的心理」。** 那就是欺骗客户。只能用一次，代价是整个生意。\n\n**根本原因：** 这些法则是为「玩家会换、彼此不再相见」的环境写的。而本地生意恰恰相反：**这是一场重复博弈，对手是同一批人，持续很多年。** 在重复博弈里，名声几乎总是胜过权谋——而耍手段的人，最后会没人愿意跟他玩。\n\n留下「读懂意图、守住自己位置」的那部分。那部分你每天都用得上。",
      it: "Delle 48 leggi, diverse funzionano in una corte del Cinquecento e ti distruggono in un negozio di quartiere. Queste sono quelle che non applicherei:\n\n• **\"Schiaccia completamente il nemico\".** In un mercato locale, il concorrente di oggi è quello che ti presta merce quando resti senza. Un'umiliazione non la dimentica nessuno.\n• **\"Usa la resa come strumento di potere\" / fingere debolezza.** Con fornitori e banche, la fama di inaffidabile ti chiude il credito per anni.\n• **\"Fa' lavorare gli altri e prenditi il merito\".** È il modo più rapido di perdere il dipendente bravo, che in una piccola attività vale più di qualsiasi tattica.\n• **\"Gioca sul bisogno della gente di credere\".** Significa ingannare i clienti. Funziona una volta e ti costa l'attività.\n\n**La ragione di fondo:** quelle leggi sono state scritte per ambienti dove i giocatori cambiano e non ci si rivede mai. Un'attività locale è l'opposto: **un gioco ripetuto, con le stesse persone, per anni.** Nei giochi ripetuti la reputazione batte l'astuzia quasi sempre — e chi bara resta senza nessuno con cui giocare.\n\nTieni la parte sul leggere le intenzioni e proteggere la tua posizione. Quella ti serve ogni giorno.",
    },
  },

  // ---------------------------------------------------------------
  // FILOSOFÍA OSCURA / PSICOLOGÍA OSCURA
  // ---------------------------------------------------------------
  {
    id: "psicologia_oscura",
    palabras: [
      "filosofia oscura", "psicologia oscura", "manipulacion", "manipular",
      "triada oscura", "maquiavelo", "maquiavelico", "persuasion oscura",
      "dark psychology", "dark triad", "psicologia sombria", "psychologie noire",
      "dunkle psychologie", "psicologia oscura", "黑暗心理学",
    ],
    respuesta: {
      es: "La llamada **psicología oscura** estudia cómo se influye en las personas sin que se den cuenta, y se asocia con la \"tríada oscura\": maquiavelismo (usar a la gente como medio), narcisismo y baja empatía.\n\nLas palancas de las que se abusa son las mismas de la persuasión normal, llevadas al engaño:\n\n• **Reciprocidad** — un regalito para crear deuda.\n• **Escasez y urgencia** — \"solo hoy\", \"queda uno\", casi siempre falsos.\n• **Prueba social** — testimonios y cifras inventadas.\n• **Autoridad** — títulos y logos que no significan nada.\n• **Compromiso** — hacerte decir un \"sí\" pequeño para arrastrarte a uno grande.\n\nY las de manipulación pura: **anclaje** (soltar un número absurdo primero para que el siguiente parezca razonable), **culpa** (\"después de todo lo que hice por ti\"), **bombardeo de amor** seguido de frialdad, y **gaslighting** (hacerte dudar de lo que viste o acordaste).\n\nMi postura al respecto: te explico esto **para que lo reconozcas cuando te lo apliquen**, que en un negocio pasa seguido — proveedores, prestamistas, \"asesores\", franquicias. Pregúntame \"cómo me defiendo de la manipulación\" para las contramedidas concretas. Como estrategia comercial propia no te la recomiendo, y te explico por qué si preguntas por \"manipular clientes\".",
      en: "So-called **dark psychology** studies how people are influenced without noticing, and is associated with the \"dark triad\": Machiavellianism (using people as means), narcissism and low empathy.\n\nThe levers it abuses are the same ones ordinary persuasion uses, pushed into deception:\n\n• **Reciprocity** — a small gift to create a debt.\n• **Scarcity and urgency** — \"today only\", \"one left\", almost always false.\n• **Social proof** — invented testimonials and figures.\n• **Authority** — titles and logos that mean nothing.\n• **Commitment** — getting a small \"yes\" out of you to drag you to a big one.\n\nAnd the purely manipulative ones: **anchoring** (throwing out an absurd number first so the next one seems reasonable), **guilt** (\"after everything I did for you\"), **love bombing** followed by coldness, and **gaslighting** (making you doubt what you saw or agreed).\n\nMy position: I explain this **so you recognise it when it's used on you**, which in business happens often — suppliers, lenders, \"advisors\", franchises. Ask me \"how do I defend against manipulation\" for concrete countermeasures. As your own commercial strategy I don't recommend it, and I'll explain why if you ask about \"manipulating customers\".",
      pt: "A chamada **psicologia sombria** estuda como se influencia as pessoas sem que percebam, e se associa à \"tríade sombria\": maquiavelismo (usar as pessoas como meio), narcisismo e baixa empatia.\n\nAs alavancas de que abusa são as mesmas da persuasão normal, levadas ao engano:\n\n• **Reciprocidade** — um presentinho para criar dívida.\n• **Escassez e urgência** — \"só hoje\", \"resta um\", quase sempre falsos.\n• **Prova social** — depoimentos e números inventados.\n• **Autoridade** — títulos e logos que não significam nada.\n• **Compromisso** — arrancar um \"sim\" pequeno para te arrastar a um grande.\n\nE as de manipulação pura: **ancoragem** (soltar um número absurdo primeiro para o seguinte parecer razoável), **culpa** (\"depois de tudo que fiz por você\"), **bombardeio de amor** seguido de frieza, e **gaslighting** (te fazer duvidar do que viu ou combinou).\n\nMinha posição: explico isso **para que reconheça quando aplicarem em você**, o que num negócio acontece muito — fornecedores, agiotas, \"consultores\", franquias. Pergunte \"como me defendo da manipulação\" para as contramedidas concretas. Como estratégia comercial própria não recomendo, e explico por quê se perguntar sobre \"manipular clientes\".",
      fr: "La **psychologie noire** étudie comment influencer les gens à leur insu, et s'associe à la « triade noire » : machiavélisme (utiliser les gens comme moyens), narcissisme et faible empathie.\n\nLes leviers dont elle abuse sont ceux de la persuasion ordinaire, poussés jusqu'à la tromperie :\n\n• **Réciprocité** — un petit cadeau pour créer une dette.\n• **Rareté et urgence** — « aujourd'hui seulement », « il en reste un », presque toujours faux.\n• **Preuve sociale** — témoignages et chiffres inventés.\n• **Autorité** — titres et logos qui ne veulent rien dire.\n• **Engagement** — vous arracher un petit « oui » pour vous entraîner vers un grand.\n\nEt les purement manipulatrices : **l'ancrage** (lancer un chiffre absurde d'abord pour que le suivant paraisse raisonnable), **la culpabilité** (« après tout ce que j'ai fait pour vous »), le **love bombing** suivi de froideur, et le **gaslighting** (vous faire douter de ce que vous avez vu ou convenu).\n\nMa position : je vous explique cela **pour que vous le reconnaissiez quand on vous l'applique**, ce qui arrive souvent en affaires — fournisseurs, prêteurs, « conseillers », franchises. Demandez-moi « comment me défendre de la manipulation » pour les contre-mesures concrètes. Comme stratégie commerciale, je ne la recommande pas, et je vous explique pourquoi si vous demandez « manipuler les clients ».",
      de: "Die sogenannte **dunkle Psychologie** untersucht, wie Menschen unbemerkt beeinflusst werden, und wird mit der „dunklen Triade\" verbunden: Machiavellismus (Menschen als Mittel benutzen), Narzissmus und geringe Empathie.\n\nDie Hebel, die sie missbraucht, sind dieselben der normalen Überzeugung, ins Täuschen getrieben:\n\n• **Reziprozität** — ein kleines Geschenk, um eine Schuld zu erzeugen.\n• **Knappheit und Dringlichkeit** — „nur heute\", „nur noch eins\", fast immer falsch.\n• **Sozialer Beweis** — erfundene Erfahrungsberichte und Zahlen.\n• **Autorität** — Titel und Logos, die nichts bedeuten.\n• **Commitment** — dir ein kleines „Ja\" entlocken, um dich zu einem großen zu ziehen.\n\nUnd die rein manipulativen: **Ankern** (zuerst eine absurde Zahl nennen, damit die nächste vernünftig wirkt), **Schuldgefühle** („nach allem, was ich für dich getan habe\"), **Love Bombing** gefolgt von Kälte, und **Gaslighting** (dich zweifeln lassen, was du gesehen oder vereinbart hast).\n\nMeine Haltung: Ich erkläre dir das, **damit du es erkennst, wenn es bei dir angewandt wird** — im Geschäft passiert das oft: Lieferanten, Geldverleiher, „Berater\", Franchises. Frag mich „wie wehre ich mich gegen Manipulation\" für konkrete Gegenmaßnahmen. Als eigene Geschäftsstrategie empfehle ich sie nicht, und ich erkläre dir warum, wenn du nach „Kunden manipulieren\" fragst.",
      zh: "所谓**黑暗心理学**研究的是如何在别人无察觉的情况下施加影响，通常与「黑暗三角」相关：马basicallyavelli主义（把人当工具）、自恋和低共情。\n\n它滥用的杠杆，其实就是普通说服术，只是推到了欺骗的一端：\n\n• **互惠** —— 送个小礼物制造亏欠感。\n• **稀缺与紧迫** —— 「仅限今天」「只剩一件」，几乎都是假的。\n• **社会认同** —— 编造的评价和数据。\n• **权威** —— 毫无意义的头衔和标志。\n• **承诺一致** —— 先让你说一个小「是」，再把你拖向大的。\n\n还有纯操纵性的手法：**锚定**（先抛出一个离谱数字，让下一个显得合理）、**愧疚**（「我为你做了这么多」）、**爱意轰炸**后接冷淡，以及**煤气灯效应**（让你怀疑自己看到或谈好的事）。\n\n我的立场：我讲这些，是**为了让你在别人对你使用时能认出来**——生意里这很常见：供应商、放贷人、「顾问」、加盟商。想要具体的应对办法，问我「怎么防范操纵」。至于把它当成自己的经营策略，我不建议，你问「操纵客户」我会说明原因。",
      it: "La cosiddetta **psicologia oscura** studia come si influenzano le persone senza che se ne accorgano, ed è associata alla \"triade oscura\": machiavellismo (usare le persone come mezzo), narcisismo e scarsa empatia.\n\nLe leve di cui abusa sono le stesse della persuasione normale, spinte fino all'inganno:\n\n• **Reciprocità** — un regalino per creare un debito.\n• **Scarsità e urgenza** — \"solo oggi\", \"ne resta uno\", quasi sempre falsi.\n• **Riprova sociale** — testimonianze e cifre inventate.\n• **Autorità** — titoli e loghi che non significano nulla.\n• **Impegno** — strapparti un piccolo \"sì\" per trascinarti a uno grande.\n\nE quelle di pura manipolazione: **ancoraggio** (buttare prima un numero assurdo perché il successivo sembri ragionevole), **senso di colpa** (\"dopo tutto quello che ho fatto per te\"), **love bombing** seguito da freddezza, e **gaslighting** (farti dubitare di ciò che hai visto o concordato).\n\nLa mia posizione: te lo spiego **perché tu lo riconosca quando lo applicano a te**, cosa che in un'attività succede spesso — fornitori, finanziatori, \"consulenti\", franchising. Chiedimi \"come mi difendo dalla manipolazione\" per le contromisure concrete. Come strategia commerciale tua non te la consiglio, e ti spiego perché se chiedi di \"manipolare i clienti\".",
    },
  },
  {
    id: "defenderse_manipulacion",
    palabras: [
      "como me defiendo de la manipulacion", "defenderme de la manipulacion",
      "no me manipulen", "me quieren ver la cara", "me estan enganando",
      "como negociar sin que me manipulen", "detectar mentiras", "presion para firmar",
      "how to defend against manipulation", "como me proteger", "se defendre",
      "manipulation erkennen", "difendersi dalla manipolazione", "识破操纵",
    ],
    respuesta: {
      es: "Estas defensas funcionan contra casi cualquier presión — un proveedor, un prestamista, un \"asesor\" que apareció solo, o un cliente que quiere condiciones imposibles:\n\n• **Regla de las 24 horas.** Nunca firmes ni decidas algo importante el mismo día que te lo proponen. La urgencia es la herramienta favorita de quien te quiere apurar: si la oferta se cae por esperar un día, no era una oferta, era una trampa.\n• **Pon los números por escrito y sácalos del cuarto.** Lejos de la persona y de su entusiasmo, las cuentas se ven distintas. Calcula el costo total anual, no el pago mensual.\n• **Ignora lo que sentiste, mira lo que te ofrecen.** Que te caiga bien no cambia los términos. Que te trate mal, tampoco.\n• **\"Déjame consultarlo\".** Aunque sea contigo mismo. Tener una instancia superior imaginaria es una defensa perfectamente legítima, y desactiva la presión al instante.\n• **Que todo quede escrito.** Lo acordado de palabra es el terreno donde vive el gaslighting: \"yo nunca dije eso\".\n• **Ten siempre una alternativa viva.** Un segundo proveedor, otra opción de crédito. La mayor parte del poder de negociación viene de poder irte de la mesa.\n\nY la señal más confiable de todas: **si te presionan para que decidas ya, la respuesta correcta casi siempre es no.**",
      en: "These defences work against almost any pressure — a supplier, a lender, an \"advisor\" who showed up out of nowhere, or a customer demanding impossible terms:\n\n• **The 24-hour rule.** Never sign or decide anything important the same day it's proposed. Urgency is the favourite tool of whoever wants to rush you: if the offer collapses because you waited a day, it wasn't an offer, it was a trap.\n• **Put the numbers in writing and take them out of the room.** Away from the person and their enthusiasm, the maths looks different. Calculate the total annual cost, not the monthly payment.\n• **Ignore how you felt, look at what you're being offered.** Liking them doesn't change the terms. Neither does them treating you badly.\n• **\"Let me check on that\".** Even if it's with yourself. Having an imaginary higher authority is a perfectly legitimate defence, and it defuses pressure instantly.\n• **Get everything in writing.** Verbal agreements are the ground where gaslighting lives: \"I never said that\".\n• **Always keep a live alternative.** A second supplier, another credit option. Most negotiating power comes from being able to walk away.\n\nAnd the most reliable signal of all: **if they're pressuring you to decide right now, the correct answer is almost always no.**",
      pt: "Estas defesas funcionam contra quase qualquer pressão — um fornecedor, um agiota, um \"consultor\" que apareceu sozinho, ou um cliente querendo condições impossíveis:\n\n• **Regra das 24 horas.** Nunca assine nem decida algo importante no mesmo dia em que te propõem. A urgência é a ferramenta favorita de quem quer te apressar: se a oferta cai por esperar um dia, não era oferta, era armadilha.\n• **Ponha os números por escrito e tire-os da sala.** Longe da pessoa e do entusiasmo dela, as contas parecem outras. Calcule o custo total anual, não a parcela.\n• **Ignore o que sentiu, olhe o que te oferecem.** Gostar dele não muda os termos. Ele te tratar mal, também não.\n• **\"Deixe-me consultar\".** Nem que seja com você mesmo. Ter uma instância superior imaginária é defesa perfeitamente legítima, e desarma a pressão na hora.\n• **Que tudo fique escrito.** O combinado de boca é o terreno onde mora o gaslighting: \"eu nunca disse isso\".\n• **Tenha sempre uma alternativa viva.** Um segundo fornecedor, outra opção de crédito. A maior parte do poder de negociação vem de poder sair da mesa.\n\nE o sinal mais confiável de todos: **se te pressionam para decidir agora, a resposta certa quase sempre é não.**",
      fr: "Ces défenses fonctionnent contre presque toute pression — un fournisseur, un prêteur, un « conseiller » venu de nulle part, ou un client aux exigences impossibles :\n\n• **La règle des 24 heures.** Ne signez et ne décidez jamais quelque chose d'important le jour même. L'urgence est l'outil préféré de qui veut vous presser : si l'offre s'effondre parce que vous avez attendu un jour, ce n'était pas une offre, c'était un piège.\n• **Mettez les chiffres par écrit et sortez-les de la pièce.** Loin de la personne et de son enthousiasme, les calculs paraissent différents. Calculez le coût total annuel, pas la mensualité.\n• **Ignorez ce que vous avez ressenti, regardez ce qu'on vous propose.** L'apprécier ne change pas les termes. Qu'il vous traite mal non plus.\n• **« Laissez-moi vérifier ».** Même si c'est avec vous-même. Avoir une autorité supérieure imaginaire est une défense parfaitement légitime, et désamorce la pression aussitôt.\n• **Que tout soit écrit.** L'accord verbal est le terrain où vit le gaslighting : « je n'ai jamais dit ça ».\n• **Gardez toujours une alternative vivante.** Un second fournisseur, une autre option de crédit. L'essentiel du pouvoir de négociation vient de pouvoir quitter la table.\n\nEt le signal le plus fiable de tous : **si l'on vous presse de décider tout de suite, la bonne réponse est presque toujours non.**",
      de: "Diese Abwehr funktioniert gegen fast jeden Druck — einen Lieferanten, einen Geldverleiher, einen „Berater\", der von selbst auftauchte, oder einen Kunden mit unmöglichen Bedingungen:\n\n• **24-Stunden-Regel.** Unterschreibe und entscheide nie etwas Wichtiges am selben Tag, an dem es vorgeschlagen wird. Dringlichkeit ist das Lieblingswerkzeug dessen, der dich hetzen will: Bricht das Angebot zusammen, weil du einen Tag gewartet hast, war es kein Angebot, sondern eine Falle.\n• **Schreib die Zahlen auf und nimm sie aus dem Raum.** Weg von der Person und ihrer Begeisterung sieht die Rechnung anders aus. Rechne die Gesamtjahreskosten, nicht die Monatsrate.\n• **Ignoriere dein Gefühl, sieh dir das Angebot an.** Ihn sympathisch zu finden ändert die Bedingungen nicht. Dass er dich schlecht behandelt, auch nicht.\n• **„Lass mich das prüfen.\"** Und sei es mit dir selbst. Eine imaginäre höhere Instanz ist eine völlig legitime Abwehr und entschärft Druck sofort.\n• **Alles schriftlich.** Mündliche Absprachen sind der Boden, auf dem Gaslighting gedeiht: „Das habe ich nie gesagt.\"\n• **Halte immer eine lebendige Alternative.** Einen zweiten Lieferanten, eine andere Kreditoption. Der größte Teil der Verhandlungsmacht kommt daraus, den Tisch verlassen zu können.\n\nUnd das verlässlichste Signal von allen: **Wenn man dich drängt, sofort zu entscheiden, ist die richtige Antwort fast immer nein.**",
      zh: "这些防线几乎能应对任何压力——供应商、放贷人、自己找上门的「顾问」，或提出不可能条件的客户：\n\n• **24 小时法则。** 重要的事，绝不在别人提出的当天签字或拍板。紧迫感是催你的人最爱的工具：如果一份报价因为你多等了一天就没了，那它不是报价，是陷阱。\n• **把数字写下来，带出那个房间。** 离开那个人和他的热情，账会看起来完全不同。算年化总成本，不是月供。\n• **别管你的感觉，看对方给的条件。** 你喜欢他，条件不会变；他态度差，条件也不会变。\n• **「我需要问一下。」** 哪怕是问你自己。有一个想象中的「上级」是完全正当的防守，能立刻卸掉压力。\n• **一切落到纸面。** 口头约定就是煤气灯效应的温床：「我从没说过那句话」。\n• **永远留一个活着的备选。** 第二家供应商、另一个借款渠道。谈判力的绝大部分，来自你随时能起身走人。\n\n还有最可靠的一个信号：**如果对方逼你现在就决定，正确答案几乎总是「不」。**",
      it: "Queste difese funzionano contro quasi ogni pressione — un fornitore, un finanziatore, un \"consulente\" comparso dal nulla, o un cliente con pretese impossibili:\n\n• **Regola delle 24 ore.** Non firmare né decidere nulla di importante lo stesso giorno in cui te lo propongono. L'urgenza è lo strumento preferito di chi vuole metterti fretta: se l'offerta crolla perché hai aspettato un giorno, non era un'offerta, era una trappola.\n• **Metti i numeri per iscritto e portali fuori dalla stanza.** Lontano dalla persona e dal suo entusiasmo, i conti sembrano altri. Calcola il costo totale annuo, non la rata.\n• **Ignora cosa hai provato, guarda cosa ti offrono.** Che ti stia simpatico non cambia le condizioni. Che ti tratti male, nemmeno.\n• **\"Fammi verificare\".** Anche solo con te stesso. Avere un'autorità superiore immaginaria è una difesa perfettamente legittima, e disinnesca la pressione all'istante.\n• **Che sia tutto scritto.** Gli accordi verbali sono il terreno dove vive il gaslighting: \"io non l'ho mai detto\".\n• **Tieni sempre viva un'alternativa.** Un secondo fornitore, un'altra opzione di credito. Gran parte del potere negoziale viene dal poterti alzare dal tavolo.\n\nE il segnale più affidabile di tutti: **se ti spingono a decidere subito, la risposta giusta è quasi sempre no.**",
    },
  },
  {
    id: "manipular_clientes",
    palabras: [
      "manipular clientes", "manipular al cliente", "convencer a como de lugar",
      "vender a la fuerza", "presionar al cliente", "trucos para vender",
      "ventas agresivas", "manipulate customers", "vendas agressivas",
      "manipuler les clients", "kunden manipulieren", "manipolare i clienti", "操纵客户",
    ],
    respuesta: {
      es: "Te lo digo directo, y no por moralina: **en un negocio local, manipular clientes es mal negocio.**\n\nLa razón es matemática, no ética. Vender con presión sube la venta de hoy y destruye lo que en realidad te sostiene: **la recompra**. Un cliente manipulado no regresa, y además habla. En un mercado donde todos se conocen, tu reputación es tu principal canal de adquisición — y es el único activo que no puedes reponer comprándolo.\n\nSuma el costo real: devoluciones, discusiones, reseñas malas, empleados que se van porque no aguantan vender así.\n\n**La alternativa no es ser pasivo, es vender mejor:**\n\n• Pregunta antes de ofrecer. Quien entiende el problema vende más que quien recita beneficios.\n• Usa urgencia y escasez **solo cuando sean verdad**. \"Me quedan dos\" siendo cierto convierte igual, y no te cuesta la credibilidad.\n• Recomienda lo más barato cuando sea lo correcto. Es lo que hace que vuelvan y traigan a otros.\n• Facilita decir que no. Paradójicamente vende más, porque baja la defensa del cliente.\n\nLas mismas palancas —reciprocidad, prueba social, autoridad— son legítimas cuando lo que comunican es cierto. La línea no está en usarlas: está en si necesitas mentir para que funcionen.",
      en: "I'll be direct, and not out of moralising: **in a local business, manipulating customers is bad business.**\n\nThe reason is mathematical, not ethical. High-pressure selling raises today's sale and destroys what actually sustains you: **repeat purchase**. A manipulated customer doesn't come back, and they talk. In a market where everyone knows everyone, your reputation is your main acquisition channel — and it's the one asset you can't restock by buying it.\n\nAdd the real cost: returns, arguments, bad reviews, employees who quit because they can't stand selling that way.\n\n**The alternative isn't being passive, it's selling better:**\n\n• Ask before you offer. Whoever understands the problem sells more than whoever recites benefits.\n• Use urgency and scarcity **only when they're true**. \"I have two left\", when true, converts just as well and costs you no credibility.\n• Recommend the cheaper option when it's the right one. That's what makes people return and bring others.\n• Make it easy to say no. Paradoxically it sells more, because it lowers the customer's guard.\n\nThe same levers — reciprocity, social proof, authority — are legitimate when what they communicate is true. The line isn't in using them: it's in whether you need to lie for them to work.",
      pt: "Vou direto, e não por moralismo: **num negócio local, manipular clientes é mau negócio.**\n\nA razão é matemática, não ética. Vender sob pressão aumenta a venda de hoje e destrói o que de fato te sustenta: **a recompra**. Um cliente manipulado não volta, e ainda fala. Num mercado onde todos se conhecem, sua reputação é seu principal canal de aquisição — e é o único ativo que não dá para repor comprando.\n\nSome o custo real: devoluções, discussões, avaliações ruins, funcionários que saem por não aguentar vender assim.\n\n**A alternativa não é ser passivo, é vender melhor:**\n\n• Pergunte antes de oferecer. Quem entende o problema vende mais que quem recita benefícios.\n• Use urgência e escassez **só quando forem verdade**. \"Restam dois\" sendo verdade converte igual, e não custa sua credibilidade.\n• Recomende o mais barato quando for o correto. É o que faz voltarem e trazerem outros.\n• Facilite dizer não. Paradoxalmente vende mais, porque baixa a defesa do cliente.\n\nAs mesmas alavancas — reciprocidade, prova social, autoridade — são legítimas quando o que comunicam é verdadeiro. A linha não está em usá-las: está em se você precisa mentir para que funcionem.",
      fr: "Je vous le dis franchement, et pas par moralisme : **dans un commerce local, manipuler les clients est une mauvaise affaire.**\n\nLa raison est mathématique, pas éthique. La vente sous pression augmente la vente du jour et détruit ce qui vous fait vivre : **le réachat**. Un client manipulé ne revient pas, et il parle. Dans un marché où tout le monde se connaît, votre réputation est votre principal canal d'acquisition — et c'est le seul actif qu'on ne peut pas réapprovisionner en l'achetant.\n\nAjoutez le coût réel : retours, disputes, mauvais avis, employés qui partent parce qu'ils ne supportent pas de vendre ainsi.\n\n**L'alternative n'est pas d'être passif, c'est de mieux vendre :**\n\n• Questionnez avant de proposer. Qui comprend le problème vend plus que qui récite des avantages.\n• N'utilisez urgence et rareté **que si elles sont vraies**. « Il m'en reste deux », quand c'est vrai, convertit tout autant sans coûter votre crédibilité.\n• Recommandez le moins cher quand c'est le bon choix. C'est ce qui fait revenir les gens et en amener d'autres.\n• Facilitez le refus. Paradoxalement cela vend plus, car cela baisse la garde du client.\n\nLes mêmes leviers — réciprocité, preuve sociale, autorité — sont légitimes quand ce qu'ils communiquent est vrai. La limite n'est pas de les utiliser : elle est de savoir si vous devez mentir pour qu'ils marchent.",
      de: "Ich sage es direkt, und nicht aus Moralpredigt: **In einem lokalen Geschäft ist Kundenmanipulation ein schlechtes Geschäft.**\n\nDer Grund ist mathematisch, nicht ethisch. Verkauf unter Druck hebt den heutigen Umsatz und zerstört das, was dich wirklich trägt: **den Wiederkauf**. Ein manipulierter Kunde kommt nicht wieder — und er redet. In einem Markt, wo jeder jeden kennt, ist dein Ruf dein wichtigster Akquisekanal — und das einzige Gut, das du nicht nachkaufen kannst.\n\nRechne die echten Kosten dazu: Retouren, Streit, schlechte Bewertungen, Mitarbeiter, die kündigen, weil sie so nicht verkaufen wollen.\n\n**Die Alternative ist nicht Passivität, sondern besser zu verkaufen:**\n\n• Frag, bevor du anbietest. Wer das Problem versteht, verkauft mehr als wer Vorteile aufsagt.\n• Nutze Dringlichkeit und Knappheit **nur, wenn sie stimmen**. „Ich habe noch zwei\" wirkt genauso, wenn es wahr ist, und kostet keine Glaubwürdigkeit.\n• Empfiehl das Günstigere, wenn es das Richtige ist. Genau das bringt Leute zurück — mit anderen im Schlepptau.\n• Mach es leicht, Nein zu sagen. Paradoxerweise verkauft das mehr, weil es die Abwehr senkt.\n\nDieselben Hebel — Reziprozität, sozialer Beweis, Autorität — sind legitim, wenn das, was sie vermitteln, wahr ist. Die Grenze liegt nicht im Benutzen: Sie liegt darin, ob du lügen musst, damit sie wirken.",
      zh: "我直说，不是讲道德：**在本地生意里，操纵客户是笔亏本买卖。**\n\n原因是算术问题，不是伦理问题。高压销售抬高了今天的成交，却毁掉了真正养活你的东西：**复购**。被操纵过的客户不会再来，而且会说出去。在人人相识的市场里，名声是你最主要的获客渠道——也是唯一一个花钱补不回来的资产。\n\n再算上真实成本：退货、争执、差评，还有受不了这种卖法而辞职的员工。\n\n**替代方案不是消极被动，而是把销售做得更好：**\n\n• 先问，再推荐。理解问题的人，比背诵卖点的人卖得多。\n• **只在属实时**使用紧迫和稀缺。「只剩两件」如果是真的，转化率一样高，还不损失可信度。\n• 该推荐便宜的就推荐便宜的。这才是让人回头、还带人来的原因。\n• 让客户容易说「不」。反而卖得更多，因为这会降低他的防备。\n\n同样的杠杆——互惠、社会认同、权威——只要传达的是事实，就是正当的。界线不在于用不用它们，而在于：你是否必须撒谎它们才管用。",
      it: "Te lo dico diretto, e non per moralismo: **in un'attività locale, manipolare i clienti è un pessimo affare.**\n\nLa ragione è matematica, non etica. Vendere sotto pressione alza la vendita di oggi e distrugge ciò che davvero ti sostiene: **il riacquisto**. Un cliente manipolato non torna, e per giunta parla. In un mercato dove tutti si conoscono, la reputazione è il tuo principale canale di acquisizione — ed è l'unico bene che non puoi riassortire comprandolo.\n\nAggiungi il costo vero: resi, discussioni, recensioni negative, dipendenti che se ne vanno perché non reggono a vendere così.\n\n**L'alternativa non è essere passivi, è vendere meglio:**\n\n• Chiedi prima di proporre. Chi capisce il problema vende più di chi recita i vantaggi.\n• Usa urgenza e scarsità **solo quando sono vere**. \"Me ne restano due\", se è vero, converte uguale e non ti costa credibilità.\n• Consiglia il più economico quando è la scelta giusta. È ciò che fa tornare le persone e portarne altre.\n• Rendi facile dire di no. Paradossalmente vende di più, perché abbassa la difesa del cliente.\n\nLe stesse leve — reciprocità, riprova sociale, autorità — sono legittime quando ciò che comunicano è vero. Il confine non sta nell'usarle: sta nel se devi mentire perché funzionino.",
    },
  },

  // ---------------------------------------------------------------
  // FILOSOFÍA DE NEGOCIO
  // ---------------------------------------------------------------
  {
    id: "estoicismo",
    palabras: [
      "estoicismo", "estoico", "marco aurelio", "seneca", "filosofia para emprender",
      "mentalidad", "como manejar el estres", "ansiedad", "estres", "angustia",
      "preocupado por el negocio", "no puedo dormir", "miedo a fracasar",
      "stoicism", "estoicismo", "stoicisme", "stoizismus", "stoicismo", "斯多葛",
    ],
    respuesta: {
      es: "El estoicismo se resume en una división: **hay cosas que dependen de ti y cosas que no.** Casi todo el sufrimiento de un dueño de negocio viene de invertir energía en las segundas.\n\n**No dependen de ti:** la economía, el clima, que abran una tienda enfrente, lo que decida un cliente, que suba el dólar.\n**Sí dependen de ti:** tus precios, tu inventario, tu trato, tu colchón de efectivo, qué tan rápido reaccionas.\n\nEl consejo práctico no es resignarse — es **dejar de gastar cabeza en lo que no mueves y poner esa energía en lo que sí.**\n\nDos ideas más que sirven mucho:\n\n• **La premeditación de lo malo.** Imagina hoy, con calma, qué harías si perdieras a tu proveedor principal o si las ventas cayeran 40%. No es pesimismo: es que el día que pase no te agarre improvisando. Casi siempre la respuesta es \"necesito un colchón y un segundo proveedor\", y eso lo puedes hacer hoy.\n• **Separa el hecho del juicio.** \"Bajaron las ventas 20%\" es un hecho. \"Soy un fracaso\" es un juicio que agregaste tú, y que además te impide pensar bien justo cuando más lo necesitas.",
      en: "Stoicism boils down to one division: **some things depend on you and some don't.** Almost all of a business owner's suffering comes from spending energy on the second kind.\n\n**Not up to you:** the economy, the weather, a shop opening across the street, what a customer decides, the exchange rate.\n**Up to you:** your prices, your inventory, how you treat people, your cash cushion, how fast you react.\n\nThe practical advice isn't resignation — it's **to stop burning your head on what you can't move and put that energy where you can.**\n\nTwo more ideas that help a lot:\n\n• **Premeditation of adversity.** Calmly imagine today what you'd do if you lost your main supplier or sales fell 40%. It's not pessimism: it's so that the day it happens you're not improvising. The answer is almost always \"I need a cushion and a second supplier\", and that you can do today.\n• **Separate the fact from the judgement.** \"Sales fell 20%\" is a fact. \"I'm a failure\" is a judgement you added, and one that stops you thinking clearly exactly when you most need to.",
      pt: "O estoicismo se resume a uma divisão: **há coisas que dependem de você e coisas que não.** Quase todo o sofrimento de um dono de negócio vem de gastar energia nas segundas.\n\n**Não dependem de você:** a economia, o clima, abrirem uma loja na frente, o que um cliente decide, o dólar subir.\n**Dependem de você:** seus preços, seu estoque, seu trato, sua reserva de caixa, quão rápido você reage.\n\nO conselho prático não é se resignar — é **parar de gastar cabeça com o que você não move e colocar essa energia no que move.**\n\nMais duas ideias muito úteis:\n\n• **A premeditação do mal.** Imagine hoje, com calma, o que faria se perdesse seu fornecedor principal ou se as vendas caíssem 40%. Não é pessimismo: é para que no dia em que acontecer você não esteja improvisando. Quase sempre a resposta é \"preciso de uma reserva e de um segundo fornecedor\", e isso dá para fazer hoje.\n• **Separe o fato do julgamento.** \"As vendas caíram 20%\" é um fato. \"Sou um fracasso\" é um julgamento que você acrescentou, e que ainda te impede de pensar bem justo quando mais precisa.",
      fr: "Le stoïcisme se résume à une division : **il y a ce qui dépend de vous et ce qui n'en dépend pas.** Presque toute la souffrance d'un patron vient de l'énergie investie dans la seconde catégorie.\n\n**Ne dépend pas de vous :** l'économie, la météo, l'ouverture d'un magasin en face, ce que décide un client, le taux de change.\n**Dépend de vous :** vos prix, votre stock, votre accueil, votre matelas de trésorerie, votre vitesse de réaction.\n\nLe conseil pratique n'est pas la résignation — c'est **d'arrêter d'user votre tête sur ce que vous ne bougez pas et de mettre cette énergie là où vous le pouvez.**\n\nDeux autres idées très utiles :\n\n• **La préméditation des maux.** Imaginez aujourd'hui, calmement, ce que vous feriez si vous perdiez votre fournisseur principal ou si les ventes chutaient de 40 %. Ce n'est pas du pessimisme : c'est pour que le jour venu vous n'improvisiez pas. La réponse est presque toujours « il me faut un matelas et un second fournisseur », et cela, vous pouvez le faire aujourd'hui.\n• **Séparez le fait du jugement.** « Les ventes ont baissé de 20 % » est un fait. « Je suis un raté » est un jugement que vous avez ajouté, et qui vous empêche de bien réfléchir au moment où vous en avez le plus besoin.",
      de: "Die Stoa lässt sich auf eine Unterscheidung bringen: **Manches hängt von dir ab, manches nicht.** Fast alles Leiden eines Unternehmers kommt daher, Energie in das Zweite zu stecken.\n\n**Hängt nicht von dir ab:** die Wirtschaft, das Wetter, dass gegenüber ein Laden aufmacht, was ein Kunde entscheidet, der Wechselkurs.\n**Hängt von dir ab:** deine Preise, dein Bestand, dein Umgang, dein Liquiditätspolster, wie schnell du reagierst.\n\nDer praktische Rat ist keine Resignation — es geht darum, **aufzuhören, den Kopf an dem zu verbrauchen, was du nicht bewegst, und diese Energie dorthin zu lenken, wo du es kannst.**\n\nZwei weitere sehr nützliche Ideen:\n\n• **Die Vorwegnahme des Schlimmen.** Stell dir heute in Ruhe vor, was du tätest, wenn du deinen Hauptlieferanten verlörst oder der Umsatz um 40 % fiele. Das ist kein Pessimismus: Es sorgt dafür, dass du am Tag X nicht improvisierst. Die Antwort lautet fast immer „ich brauche ein Polster und einen zweiten Lieferanten\" — und das kannst du heute tun.\n• **Trenne die Tatsache vom Urteil.** „Der Umsatz ist um 20 % gefallen\" ist eine Tatsache. „Ich bin ein Versager\" ist ein Urteil, das du hinzugefügt hast — und das dich genau dann am klaren Denken hindert, wenn du es am nötigsten hast.",
      zh: "斯多葛哲学可以归结为一个区分：**有些事取决于你，有些不取决于你。** 生意人的痛苦，几乎都来自把精力花在后者上。\n\n**不取决于你：** 经济大势、天气、对面开了家店、客户怎么决定、汇率涨了。\n**取决于你：** 你的定价、你的库存、你待人的方式、你的现金缓冲、你反应有多快。\n\n实用的建议不是认命——而是**别再把脑力耗在你推不动的事上，把那份精力放到你推得动的地方。**\n\n另外两个很管用的观念：\n\n• **预想坏事。** 今天就心平气和地想一想：如果失去主要供应商，或销量掉 40%，你会怎么做。这不是悲观：而是让那天真来临时，你不用临场发挥。答案几乎总是「我需要一笔缓冲金和第二家供应商」——而这件事今天就能做。\n• **把事实和评判分开。** 「销量下降了 20%」是事实。「我是个失败者」是你自己加上去的评判，而且它恰恰在你最需要清醒思考的时候，让你想不清楚。",
      it: "Lo stoicismo si riassume in una distinzione: **ci sono cose che dipendono da te e cose che no.** Quasi tutta la sofferenza di un titolare viene dall'investire energia nelle seconde.\n\n**Non dipendono da te:** l'economia, il tempo, che aprano un negozio di fronte, cosa decide un cliente, il cambio.\n**Dipendono da te:** i tuoi prezzi, il tuo magazzino, il tuo modo di trattare le persone, il tuo cuscinetto di cassa, quanto in fretta reagisci.\n\nIl consiglio pratico non è rassegnarsi — è **smettere di consumare testa su ciò che non muovi e mettere quell'energia dove puoi.**\n\nAltre due idee molto utili:\n\n• **La premeditazione dei mali.** Immagina oggi, con calma, cosa faresti se perdessi il fornitore principale o se le vendite calassero del 40%. Non è pessimismo: serve perché il giorno in cui succede non ti trovi a improvvisare. La risposta è quasi sempre \"mi serve un cuscinetto e un secondo fornitore\", e quello puoi farlo oggi.\n• **Separa il fatto dal giudizio.** \"Le vendite sono calate del 20%\" è un fatto. \"Sono un fallito\" è un giudizio che hai aggiunto tu, e che per giunta ti impedisce di ragionare proprio quando serve di più.",
    },
  },
  {
    id: "largo_plazo",
    palabras: [
      "largo plazo", "corto plazo", "pensar a largo plazo", "paciencia",
      "interes compuesto", "juego infinito", "vision de negocio", "sostenible",
      "long term", "longo prazo", "long terme", "langfristig", "lungo termine", "长期",
    ],
    respuesta: {
      es: "Casi todas las decisiones difíciles de un negocio se aclaran con una sola pregunta: **¿esto lo estoy haciendo para hoy o para dentro de tres años?**\n\nLos negocios locales son **juegos repetidos**: los mismos clientes, los mismos proveedores, la misma gente, por años. En un juego repetido, lo que se acumula gana:\n\n• Un cliente bien atendido no vale una venta, vale diez años de compras y la gente que trae.\n• Un proveedor con el que siempre cumpliste te salva el día que necesitas mercancía a crédito.\n• Una reputación limpia baja tu costo de conseguir clientes a casi cero.\n\nLo contrario también se acumula: cada atajo, cada cliente exprimido, cada promesa incumplida, se guarda en la memoria del mercado.\n\n**El truco práctico:** cuando dudes entre ganar $500 hoy y quedar bien, pregúntate cuánto vale ese cliente si vuelve doce veces al año durante cinco años. Casi siempre el número te decide solo.\n\nY el otro lado de la moneda: **paciencia no es lentitud.** A largo plazo también hay que decidir rápido — lo que no se hace es sacrificar el futuro por el mes.",
      en: "Almost every hard business decision clears up with one question: **am I doing this for today or for three years from now?**\n\nLocal businesses are **repeated games**: the same customers, the same suppliers, the same people, for years. In a repeated game, whatever compounds wins:\n\n• A well-served customer isn't worth one sale, it's worth ten years of purchases plus the people they bring.\n• A supplier you always delivered on saves you the day you need goods on credit.\n• A clean reputation drops your cost of acquiring customers to almost zero.\n\nThe opposite compounds too: every shortcut, every squeezed customer, every broken promise gets filed in the market's memory.\n\n**The practical trick:** when torn between making $500 today and doing right by someone, ask what that customer is worth if they come back twelve times a year for five years. The number almost always decides for you.\n\nAnd the other side of the coin: **patience isn't slowness.** Playing long-term still means deciding fast — what you don't do is sacrifice the future for the month.",
      pt: "Quase todas as decisões difíceis de um negócio se esclarecem com uma pergunta: **estou fazendo isso para hoje ou para daqui a três anos?**\n\nNegócios locais são **jogos repetidos**: os mesmos clientes, os mesmos fornecedores, as mesmas pessoas, por anos. Num jogo repetido, o que se acumula vence:\n\n• Um cliente bem atendido não vale uma venda, vale dez anos de compras e as pessoas que ele traz.\n• Um fornecedor com quem você sempre cumpriu te salva no dia em que precisa de mercadoria a prazo.\n• Uma reputação limpa derruba seu custo de conseguir clientes para quase zero.\n\nO contrário também se acumula: cada atalho, cada cliente espremido, cada promessa quebrada fica guardado na memória do mercado.\n\n**O truque prático:** quando estiver em dúvida entre ganhar $500 hoje e ficar bem, pergunte quanto vale aquele cliente se voltar doze vezes por ano durante cinco anos. Quase sempre o número decide sozinho.\n\nE o outro lado da moeda: **paciência não é lentidão.** No longo prazo também é preciso decidir rápido — o que não se faz é sacrificar o futuro pelo mês.",
      fr: "Presque toutes les décisions difficiles s'éclaircissent avec une seule question : **est-ce que je fais ça pour aujourd'hui ou pour dans trois ans ?**\n\nLes commerces locaux sont des **jeux répétés** : les mêmes clients, les mêmes fournisseurs, les mêmes gens, pendant des années. Dans un jeu répété, ce qui s'accumule gagne :\n\n• Un client bien servi ne vaut pas une vente, il vaut dix ans d'achats plus les gens qu'il amène.\n• Un fournisseur envers qui vous avez toujours tenu parole vous sauve le jour où il vous faut de la marchandise à crédit.\n• Une réputation propre fait tomber votre coût d'acquisition à presque zéro.\n\nL'inverse s'accumule aussi : chaque raccourci, chaque client pressuré, chaque promesse non tenue s'inscrit dans la mémoire du marché.\n\n**L'astuce pratique :** quand vous hésitez entre gagner 500 $ aujourd'hui et bien faire, demandez-vous ce que vaut ce client s'il revient douze fois par an pendant cinq ans. Le chiffre décide presque toujours pour vous.\n\nEt le revers : **la patience n'est pas la lenteur.** Jouer sur le long terme demande aussi de décider vite — ce qu'on ne fait pas, c'est sacrifier l'avenir pour le mois.",
      de: "Fast jede schwierige Entscheidung klärt sich mit einer Frage: **Mache ich das für heute oder für in drei Jahren?**\n\nLokale Betriebe sind **wiederholte Spiele**: dieselben Kunden, dieselben Lieferanten, dieselben Leute, über Jahre. In einem wiederholten Spiel gewinnt, was sich aufsummiert:\n\n• Ein gut bedienter Kunde ist nicht einen Verkauf wert, sondern zehn Jahre Einkäufe plus die Leute, die er mitbringt.\n• Ein Lieferant, dem gegenüber du immer Wort gehalten hast, rettet dich an dem Tag, an dem du Ware auf Kredit brauchst.\n• Ein sauberer Ruf senkt deine Kosten der Kundengewinnung auf fast null.\n\nDas Gegenteil summiert sich ebenso: jede Abkürzung, jeder ausgequetschte Kunde, jedes gebrochene Versprechen landet im Gedächtnis des Marktes.\n\n**Der praktische Kniff:** Wenn du zwischen 500 $ heute und Anstand schwankst, frag, was dieser Kunde wert ist, wenn er zwölfmal im Jahr fünf Jahre lang wiederkommt. Die Zahl entscheidet fast immer von selbst.\n\nUnd die Kehrseite: **Geduld ist nicht Langsamkeit.** Langfristig zu spielen heißt trotzdem, schnell zu entscheiden — was man nicht tut, ist die Zukunft für den Monat zu opfern.",
      zh: "生意上几乎所有难做的决定，用一个问题就能理清：**这件事我是为今天做的，还是为三年后做的？**\n\n本地生意是**重复博弈**：同一批客户、同一批供应商、同一群人，持续很多年。在重复博弈里，能累积的东西才会赢：\n\n• 一个被服务好的客户，值的不是一单生意，而是十年的消费加上他带来的人。\n• 一个你始终守信的供应商，会在你需要赊货的那天救你。\n• 干净的名声，能把你的获客成本压到接近零。\n\n反面同样会累积：每一次抄近路、每一个被榨过的客户、每一个没兑现的承诺，都会存进市场的记忆里。\n\n**实用技巧：** 当你在「今天赚 500 块」和「把事做对」之间犹豫时，算一下：如果这个客户一年回来十二次、持续五年，他值多少？这个数字几乎总能替你做决定。\n\n还有硬币的另一面：**耐心不等于慢。** 做长期主义者，照样要决策果断——你不做的，是拿未来换这个月。",
      it: "Quasi tutte le decisioni difficili si chiariscono con una domanda: **lo sto facendo per oggi o per fra tre anni?**\n\nLe attività locali sono **giochi ripetuti**: gli stessi clienti, gli stessi fornitori, le stesse persone, per anni. In un gioco ripetuto vince ciò che si accumula:\n\n• Un cliente servito bene non vale una vendita, vale dieci anni di acquisti più le persone che porta.\n• Un fornitore con cui hai sempre mantenuto la parola ti salva il giorno in cui ti serve merce a credito.\n• Una reputazione pulita abbatte quasi a zero il costo di acquisire clienti.\n\nAnche il contrario si accumula: ogni scorciatoia, ogni cliente spremuto, ogni promessa non mantenuta finisce nella memoria del mercato.\n\n**Il trucco pratico:** quando sei combattuto tra guadagnare 500 $ oggi e fare la cosa giusta, chiediti quanto vale quel cliente se torna dodici volte l'anno per cinque anni. Quasi sempre il numero decide da solo.\n\nE l'altra faccia della medaglia: **pazienza non è lentezza.** Giocare a lungo termine richiede comunque di decidere in fretta — ciò che non si fa è sacrificare il futuro per il mese.",
    },
  },
  {
    id: "riesgo_ruina",
    palabras: [
      "riesgo", "arriesgar", "apostar todo", "riesgo de ruina", "quebrar",
      "todo o nada", "hasta cuanto arriesgar", "antifragil", "cisne negro",
      "risk of ruin", "risco", "risque", "risiko", "rischio", "风险",
    ],
    respuesta: {
      es: "Hay una regla que vale más que cualquier estrategia: **nunca arriesgues una cantidad que, si la pierdes, te saca del juego.**\n\nLa razón es que las probabilidades no importan si el resultado es definitivo. Una apuesta con 90% de éxito suena buenísima, pero si el 10% restante significa cerrar, y la repites varias veces, la quiebra deja de ser posibilidad y se vuelve cuestión de tiempo. **Sobrevivir es la condición para todo lo demás.**\n\nEn la práctica:\n\n• No pongas todo tu capital en un solo pedido, por muy buena que sea la oferta.\n• No dependas de un solo proveedor, un solo cliente grande, ni un solo producto. Si un cliente es más del 30% de tus ventas, no es tu mejor cliente: es tu mayor riesgo.\n• No uses el dinero de la nómina o de los impuestos para una oportunidad.\n• Antes de cualquier decisión grande, pregunta: **¿qué pasa si sale mal? ¿sigo abierto?** Si la respuesta es no, no importa qué tan buena se vea.\n\nY el otro lado: **apuestas chicas y frecuentes sí valen.** Prueba productos nuevos con poco inventario, prueba precios, prueba horarios. Muchos experimentos baratos donde lo máximo que pierdes es pequeño, y de vez en cuando uno paga por todos.",
      en: "There's one rule worth more than any strategy: **never risk an amount that, if you lose it, takes you out of the game.**\n\nThe reason is that probabilities don't matter if the outcome is final. A bet with a 90% success rate sounds great, but if the remaining 10% means closing down, and you repeat it several times, bankruptcy stops being a possibility and becomes a matter of time. **Surviving is the precondition for everything else.**\n\nIn practice:\n\n• Don't put all your capital into a single order, however good the deal.\n• Don't depend on one supplier, one big customer, or one product. If a customer is more than 30% of your sales, they're not your best customer: they're your biggest risk.\n• Don't use payroll or tax money for an opportunity.\n• Before any big decision, ask: **what if it goes wrong? am I still open?** If the answer is no, it doesn't matter how good it looks.\n\nAnd the flip side: **small, frequent bets are worth it.** Test new products with little inventory, test prices, test hours. Many cheap experiments where the most you can lose is small, and every so often one pays for all the rest.",
      pt: "Há uma regra que vale mais que qualquer estratégia: **nunca arrisque uma quantia que, se você perder, te tira do jogo.**\n\nA razão é que as probabilidades não importam se o resultado é definitivo. Uma aposta com 90% de sucesso soa ótima, mas se os 10% restantes significam fechar, e você repete várias vezes, a falência deixa de ser possibilidade e vira questão de tempo. **Sobreviver é a condição para todo o resto.**\n\nNa prática:\n\n• Não coloque todo seu capital em um único pedido, por melhor que seja a oferta.\n• Não dependa de um só fornecedor, um só cliente grande, nem um só produto. Se um cliente é mais de 30% das suas vendas, não é seu melhor cliente: é seu maior risco.\n• Não use o dinheiro da folha ou dos impostos para uma oportunidade.\n• Antes de qualquer decisão grande, pergunte: **e se der errado? continuo aberto?** Se a resposta é não, não importa quão boa pareça.\n\nE o outro lado: **apostas pequenas e frequentes valem sim.** Teste produtos novos com pouco estoque, teste preços, teste horários. Muitos experimentos baratos onde o máximo que você perde é pouco, e de vez em quando um paga por todos.",
      fr: "Il existe une règle qui vaut plus que n'importe quelle stratégie : **ne risquez jamais une somme qui, si vous la perdez, vous sort du jeu.**\n\nLa raison : les probabilités ne comptent pas si l'issue est définitive. Un pari à 90 % de réussite paraît excellent, mais si les 10 % restants signifient fermer, et que vous le répétez plusieurs fois, la faillite cesse d'être une possibilité pour devenir une question de temps. **Survivre est la condition de tout le reste.**\n\nEn pratique :\n\n• Ne mettez pas tout votre capital dans une seule commande, aussi bonne soit l'affaire.\n• Ne dépendez ni d'un seul fournisseur, ni d'un seul gros client, ni d'un seul produit. Si un client représente plus de 30 % de vos ventes, ce n'est pas votre meilleur client : c'est votre plus grand risque.\n• N'utilisez pas l'argent des salaires ou des impôts pour une opportunité.\n• Avant toute grande décision, demandez : **et si ça tourne mal ? suis-je encore ouvert ?** Si la réponse est non, peu importe à quel point ça paraît beau.\n\nEt l'envers : **les petits paris fréquents, eux, valent le coup.** Testez de nouveaux produits avec peu de stock, testez des prix, testez des horaires. Beaucoup d'expériences bon marché où la perte maximale reste petite, et de temps en temps l'une d'elles paie pour toutes les autres.",
      de: "Es gibt eine Regel, die mehr wert ist als jede Strategie: **Riskiere nie einen Betrag, der dich, wenn du ihn verlierst, aus dem Spiel nimmt.**\n\nDer Grund: Wahrscheinlichkeiten zählen nicht, wenn das Ergebnis endgültig ist. Eine Wette mit 90 % Erfolg klingt großartig — aber wenn die restlichen 10 % Schließung bedeuten und du sie mehrfach wiederholst, ist der Bankrott keine Möglichkeit mehr, sondern eine Frage der Zeit. **Überleben ist die Bedingung für alles andere.**\n\nIn der Praxis:\n\n• Steck nicht dein ganzes Kapital in eine einzige Bestellung, wie gut das Angebot auch sei.\n• Häng nicht an einem Lieferanten, einem Großkunden oder einem Produkt. Macht ein Kunde mehr als 30 % deines Umsatzes aus, ist er nicht dein bester Kunde, sondern dein größtes Risiko.\n• Nutze kein Lohn- oder Steuergeld für eine Gelegenheit.\n• Frag vor jeder großen Entscheidung: **Was, wenn es schiefgeht? Habe ich dann noch offen?** Lautet die Antwort nein, ist egal, wie gut es aussieht.\n\nUnd die Kehrseite: **Kleine, häufige Wetten lohnen sich sehr wohl.** Teste neue Produkte mit wenig Bestand, teste Preise, teste Öffnungszeiten. Viele billige Experimente, bei denen der Höchstverlust klein bleibt — und ab und zu zahlt eines für alle anderen.",
      zh: "有一条规则，比任何策略都值钱：**永远不要押上一笔「输了就出局」的钱。**\n\n原因在于：如果结果是不可逆的，概率就不重要了。一个成功率 90% 的赌注听起来很棒，但如果剩下的 10% 意味着关门，而你反复押注，那破产就不再是可能性，而是时间问题。**活下来是其他一切的前提。**\n\n具体来说：\n\n• 别把全部资金压在一次进货上，不管这个价多划算。\n• 别依赖单一供应商、单一大客户、单一产品。如果一个客户占了你销售额的 30% 以上，他不是你最好的客户，而是你最大的风险。\n• 别动发工资的钱和税款去抓「机会」。\n• 任何重大决定之前先问：**如果搞砸了会怎样？我还开得下去吗？** 如果答案是否定的，它看起来再美也不重要。\n\n另一面是：**小额、频繁的下注是值得的。** 用少量库存试新品、试价格、试营业时间。做大量便宜的试验，最多亏一点点，而偶尔有一次的收获能覆盖掉全部。",
      it: "C'è una regola che vale più di qualsiasi strategia: **non rischiare mai una cifra che, se la perdi, ti butta fuori dal gioco.**\n\nIl motivo è che le probabilità non contano se l'esito è definitivo. Una scommessa con il 90% di successo sembra ottima, ma se il restante 10% significa chiudere, e la ripeti più volte, il fallimento smette di essere una possibilità e diventa una questione di tempo. **Sopravvivere è la condizione di tutto il resto.**\n\nIn pratica:\n\n• Non mettere tutto il capitale in un solo ordine, per quanto buona sia l'offerta.\n• Non dipendere da un solo fornitore, un solo grande cliente, un solo prodotto. Se un cliente è più del 30% delle tue vendite, non è il tuo miglior cliente: è il tuo rischio più grande.\n• Non usare i soldi degli stipendi o delle tasse per un'occasione.\n• Prima di ogni decisione grande chiediti: **e se va male? resto aperto?** Se la risposta è no, non importa quanto sembri buona.\n\nE il rovescio: **le scommesse piccole e frequenti valgono eccome.** Prova prodotti nuovi con poco magazzino, prova i prezzi, prova gli orari. Tanti esperimenti economici dove il massimo che perdi è poco, e ogni tanto uno ripaga tutti gli altri.",
    },
  },
  {
    id: "ego_fracaso",
    palabras: [
      "ego", "por que fracasan los negocios", "fracaso", "cerre mi negocio",
      "errores de emprendedores", "orgullo", "necedad", "aprender del error",
      "why businesses fail", "fracasso", "echec", "scheitern", "fallimento", "为什么失败",
    ],
    respuesta: {
      es: "Los negocios rara vez cierran por una sola cosa espectacular. Casi siempre es una lista corta y muy repetida:\n\n• **Se quedaron sin efectivo**, no sin ventas. Es la causa número uno.\n• **Confundieron caja con ganancia** y gastaron dinero que ya estaba comprometido.\n• **Crecieron antes de tiempo.** Duplicaron costos fijos con una buena racha que no duró.\n• **No conocían sus números.** Trabajaron años vendiendo algo a pérdida sin saberlo.\n• **Dependían de uno solo:** un cliente, un proveedor, un producto.\n• **El dueño no soltó nada** y se convirtió en el cuello de botella de todo.\n\nY debajo de varias de esas hay una misma raíz: **el ego.** Se manifiesta como no bajar el precio de lo que no se vende por orgullo, no pedir ayuda, no despedir a quien hay que despedir, no reconocer que la idea no funcionó, o gastar en apariencias en vez de en el negocio.\n\n**La postura útil:** separa tu identidad de tu negocio. Que una decisión salga mal no dice nada de ti, dice algo del mercado — y esa información vale dinero si la escuchas rápido. Los que sobreviven no son los que no se equivocan: son los que se equivocan barato y cambian de opinión sin drama.",
      en: "Businesses rarely close because of one spectacular thing. It's almost always a short, very repetitive list:\n\n• **They ran out of cash**, not out of sales. That's the number one cause.\n• **They confused cash with profit** and spent money that was already committed.\n• **They grew too early.** They doubled fixed costs on a good streak that didn't last.\n• **They didn't know their numbers.** They spent years selling something at a loss without realising.\n• **They depended on just one:** one customer, one supplier, one product.\n• **The owner let go of nothing** and became the bottleneck for everything.\n\nAnd underneath several of those is one common root: **ego.** It shows up as refusing to discount what isn't selling out of pride, not asking for help, not firing who needs firing, not admitting the idea didn't work, or spending on appearances instead of on the business.\n\n**The useful stance:** separate your identity from your business. A decision going badly says nothing about you, it says something about the market — and that information is worth money if you listen fast. The ones who survive aren't those who never get it wrong: they're the ones who get it wrong cheaply and change their minds without drama.",
      pt: "Negócios raramente fecham por uma única coisa espetacular. Quase sempre é uma lista curta e muito repetida:\n\n• **Ficaram sem caixa**, não sem vendas. É a causa número um.\n• **Confundiram caixa com lucro** e gastaram dinheiro já comprometido.\n• **Cresceram antes da hora.** Dobraram custos fixos com uma boa fase que não durou.\n• **Não conheciam seus números.** Passaram anos vendendo algo no prejuízo sem saber.\n• **Dependiam de um só:** um cliente, um fornecedor, um produto.\n• **O dono não soltou nada** e virou o gargalo de tudo.\n\nE embaixo de várias dessas há a mesma raiz: **o ego.** Aparece como não baixar o preço do que não vende por orgulho, não pedir ajuda, não demitir quem precisa ser demitido, não reconhecer que a ideia não funcionou, ou gastar em aparências em vez de no negócio.\n\n**A postura útil:** separe sua identidade do seu negócio. Uma decisão dar errado não diz nada sobre você, diz algo sobre o mercado — e essa informação vale dinheiro se você escutar rápido. Os que sobrevivem não são os que não erram: são os que erram barato e mudam de ideia sem drama.",
      fr: "Les entreprises ferment rarement à cause d'une seule chose spectaculaire. C'est presque toujours une liste courte et très répétitive :\n\n• **Elles ont manqué de trésorerie**, pas de ventes. C'est la cause numéro un.\n• **Elles ont confondu caisse et bénéfice** et dépensé de l'argent déjà engagé.\n• **Elles ont grandi trop tôt.** Elles ont doublé les frais fixes sur une bonne période qui n'a pas duré.\n• **Elles ne connaissaient pas leurs chiffres.** Des années à vendre à perte sans le savoir.\n• **Elles dépendaient d'un seul :** un client, un fournisseur, un produit.\n• **Le patron n'a rien lâché** et est devenu le goulot d'étranglement de tout.\n\nEt sous plusieurs de ces points, une même racine : **l'ego.** Il se manifeste par le refus de brader ce qui ne se vend pas, ne pas demander d'aide, ne pas licencier qui doit l'être, ne pas reconnaître que l'idée n'a pas marché, ou dépenser en apparences plutôt que dans l'entreprise.\n\n**La posture utile :** séparez votre identité de votre entreprise. Une décision qui tourne mal ne dit rien de vous, elle dit quelque chose du marché — et cette information vaut de l'argent si vous l'écoutez vite. Ceux qui survivent ne sont pas ceux qui ne se trompent jamais : ce sont ceux qui se trompent à bas prix et changent d'avis sans drame.",
      de: "Betriebe schließen selten wegen einer einzigen spektakulären Sache. Fast immer ist es eine kurze, sehr wiederkehrende Liste:\n\n• **Das Geld ging aus**, nicht die Verkäufe. Ursache Nummer eins.\n• **Sie verwechselten Kasse mit Gewinn** und gaben Geld aus, das schon verplant war.\n• **Sie wuchsen zu früh.** Fixkosten verdoppelt auf einer guten Phase, die nicht hielt.\n• **Sie kannten ihre Zahlen nicht.** Jahrelang etwas mit Verlust verkauft, ohne es zu merken.\n• **Sie hingen an einem Einzigen:** einem Kunden, einem Lieferanten, einem Produkt.\n• **Der Inhaber gab nichts ab** und wurde zum Engpass für alles.\n\nUnter mehreren davon liegt dieselbe Wurzel: **das Ego.** Es zeigt sich darin, aus Stolz nicht zu reduzieren, was liegen bleibt, keine Hilfe zu holen, nicht zu entlassen, wer entlassen gehört, nicht einzugestehen, dass die Idee nicht funktioniert hat, oder in Fassade statt in den Betrieb zu investieren.\n\n**Die nützliche Haltung:** Trenne deine Identität von deinem Betrieb. Dass eine Entscheidung schiefgeht, sagt nichts über dich, sondern etwas über den Markt — und diese Information ist Geld wert, wenn du schnell hinhörst. Die Überlebenden sind nicht die, die sich nie irren: Es sind die, die sich billig irren und ohne Drama ihre Meinung ändern.",
      zh: "生意很少是因为某一件轰轰烈烈的事而倒闭。几乎总是那份很短、很重复的清单：\n\n• **现金断了**，而不是没销量。这是头号原因。\n• **把收到的钱当成利润**，花掉了其实已有去处的钱。\n• **过早扩张。** 靠一段没能持续的好行情，把固定成本翻了倍。\n• **不懂自己的数字。** 亏本卖了好几年都不知道。\n• **只依赖一个：** 一个客户、一个供应商、一个产品。\n• **老板什么都不放手**，自己成了所有事的瓶颈。\n\n而这几条底下，有一个共同的根源：**自我（ego）。** 它表现为：因为面子不肯给滞销品降价、不肯求助、该辞的人不辞、不承认这个想法没跑通、把钱花在门面而不是生意上。\n\n**有用的姿态：** 把你的身份认同和你的生意分开。一个决定失败，说明的不是你这个人，而是市场——只要你听得够快，这条信息很值钱。活下来的人不是从不犯错的人，而是**错得便宜、并且能不带情绪地改主意**的人。",
      it: "Le attività raramente chiudono per una sola cosa spettacolare. Quasi sempre è un elenco corto e molto ripetitivo:\n\n• **Sono rimaste senza cassa**, non senza vendite. È la causa numero uno.\n• **Hanno confuso cassa con profitto** e speso denaro già impegnato.\n• **Sono cresciute troppo presto.** Hanno raddoppiato i costi fissi su un buon periodo che non è durato.\n• **Non conoscevano i propri numeri.** Anni a vendere qualcosa in perdita senza saperlo.\n• **Dipendevano da uno solo:** un cliente, un fornitore, un prodotto.\n• **Il titolare non ha mollato nulla** ed è diventato il collo di bottiglia di tutto.\n\nE sotto diverse di queste c'è la stessa radice: **l'ego.** Si manifesta nel non svendere per orgoglio ciò che non vende, non chiedere aiuto, non licenziare chi va licenziato, non ammettere che l'idea non ha funzionato, o spendere in apparenza invece che nell'attività.\n\n**L'atteggiamento utile:** separa la tua identità dalla tua attività. Che una decisione vada male non dice nulla di te, dice qualcosa del mercato — e quell'informazione vale soldi se la ascolti in fretta. Chi sopravvive non è chi non sbaglia mai: è chi sbaglia a poco prezzo e cambia idea senza drammi.",
    },
  },
];
