import { TemaConocimiento } from "./conocimiento";

// Cuarto bloque: cosas que no tienen NADA que ver con CoreStock ni con
// los datos del negocio — impuestos, bancos, tarjetas, fraudes, cripto,
// retiro. Son las preguntas que alguien le hace a un asistente cuando
// deja de tratarlo como un menú y empieza a tratarlo como alguien a
// quien preguntarle.
//
// Dos reglas al escribir esto:
//
// 1. Donde la respuesta depende del país se dice, y se usa México como
//    ejemplo concreto en vez de hablar en abstracto — pero se aclara que
//    es el ejemplo, no la regla universal.
// 2. Nada de consejo que solo un profesional puede dar sin conocer el
//    caso. Cuando la respuesta correcta es "ve con un contador", eso es
//    lo que dice, en vez de fingir una certeza que no tiene.
export const TEMAS_GENERAL: TemaConocimiento[] = [
  {
    id: "impuestos_basicos",
    titulo: { es: "IVA e ISR explicados simple", en: "VAT and income tax, simply", pt: "IVA e imposto de renda, simples", fr: "TVA et impôt sur le revenu", de: "Mehrwertsteuer und Einkommensteuer", it: "IVA e imposte sul reddito", zh: "增值税和所得税" },
    relacionados: ["separar_finanzas", "factura_cfdi", "flujo_caja"],
    palabras: ["impuestos", "el iva", "de iva", "pagar iva", "iva e isr", "el isr", "cuanto pago de impuestos", "que impuestos pago", "declaracion", "sat", "hacienda", "taxes", "vat", "income tax", "impostos", "impots", "steuern", "tasse", "税"],
    respuesta: {
      es: "Hay dos impuestos que confunden a casi todo el mundo, y confundirlos cuesta caro:\n\n**El IVA no es tuyo.** Cuando cobras 116 por algo de 100, esos 16 son del gobierno: los estás guardando un rato. El error clásico es gastarte ese dinero porque está en tu cuenta, y luego no tenerlo cuando toca pagar. Trátalo como dinero ajeno desde el primer día.\n\n**El ISR sí sale de tu ganancia.** Se calcula sobre lo que ganaste, no sobre lo que vendiste. Por eso guardar tus comprobantes de compra importa tanto: cada gasto legítimo que puedes comprobar baja la base sobre la que pagas.\n\nLa regla práctica: aparta un porcentaje fijo de cada venta en una cuenta separada, el mismo día. Si no lo apartas cuando entra, no va a estar cuando salga.\n\nLos porcentajes y regímenes cambian por país y por tu nivel de ingresos — en México el Régimen Simplificado de Confianza es mucho más barato para un negocio chico que el general. Esa parte sí revísala con un contador: es de las pocas cosas donde pagar por un consejo se paga solo.",
      en: "Two taxes confuse almost everyone, and confusing them is expensive:\n\n**VAT isn't yours.** When you charge 116 for something priced at 100, those 16 belong to the government — you're just holding them for a while. The classic mistake is spending that money because it's sitting in your account, then not having it when payment is due. Treat it as someone else's money from day one.\n\n**Income tax does come out of your profit.** It's calculated on what you earned, not what you sold. That's why keeping your purchase receipts matters so much: every legitimate expense you can prove lowers the base you pay on.\n\nThe practical rule: set aside a fixed percentage of every sale into a separate account, the same day. If you don't set it aside when it comes in, it won't be there when it goes out.\n\nRates and tax regimes vary by country and by your income level — in Mexico the Simplified Trust Regime is far cheaper for a small business than the general one. Do check that part with an accountant: it's one of the few things where paying for advice pays for itself.",
      pt: "Dois impostos confundem quase todo mundo, e confundi-los sai caro:\n\n**O imposto sobre vendas não é seu.** Quando você cobra 116 por algo de 100, esses 16 são do governo: você só está guardando por um tempo. O erro clássico é gastar esse dinheiro porque está na sua conta, e depois não tê-lo na hora de pagar. Trate como dinheiro alheio desde o primeiro dia.\n\n**O imposto de renda sai do seu lucro.** É calculado sobre o que você ganhou, não sobre o que vendeu. Por isso guardar seus comprovantes de compra importa tanto: cada despesa legítima que você consegue comprovar diminui a base sobre a qual paga.\n\nA regra prática: separe um percentual fixo de cada venda numa conta separada, no mesmo dia. Se não separar quando entra, não vai estar lá quando sair.\n\nAs alíquotas e regimes mudam por país e pelo seu nível de faturamento. Essa parte vale revisar com um contador: é uma das poucas coisas onde pagar por um conselho se paga sozinho.",
      fr: "Deux impôts embrouillent presque tout le monde, et les confondre coûte cher :\n\n**La TVA n'est pas à vous.** Quand vous facturez 116 pour un produit à 100, ces 16 appartiennent à l'État : vous les gardez un moment, c'est tout. L'erreur classique est de dépenser cet argent parce qu'il est sur le compte, puis de ne plus l'avoir à l'échéance. Traitez-le comme l'argent d'un autre dès le premier jour.\n\n**L'impôt sur le revenu, lui, sort de votre bénéfice.** Il se calcule sur ce que vous avez gagné, pas sur ce que vous avez vendu. C'est pourquoi conserver vos justificatifs d'achat compte autant : chaque dépense légitime prouvée abaisse la base imposable.\n\nLa règle pratique : mettez de côté un pourcentage fixe de chaque vente sur un compte séparé, le jour même. Si vous ne le mettez pas de côté à l'entrée, il ne sera pas là à la sortie.\n\nLes taux et régimes varient selon le pays et votre niveau de revenus. Cette partie-là, voyez-la avec un comptable : c'est l'une des rares dépenses de conseil qui se rembourse toute seule.",
      de: "Zwei Steuern verwirren fast jeden, und die Verwechslung ist teuer:\n\n**Die Mehrwertsteuer gehört dir nicht.** Wenn du 116 für etwas berechnest, das 100 kostet, gehören diese 16 dem Staat — du hältst sie nur eine Weile. Der klassische Fehler: dieses Geld ausgeben, weil es auf dem Konto liegt, und es dann bei Fälligkeit nicht haben. Behandle es vom ersten Tag an als fremdes Geld.\n\n**Die Einkommensteuer kommt dagegen aus deinem Gewinn.** Sie wird auf das berechnet, was du verdient hast, nicht auf das, was du verkauft hast. Deshalb sind Einkaufsbelege so wichtig: Jede nachweisbare Betriebsausgabe senkt die Bemessungsgrundlage.\n\nDie praktische Regel: Leg von jedem Verkauf noch am selben Tag einen festen Prozentsatz auf ein separates Konto. Was du beim Eingang nicht zurücklegst, ist beim Ausgang nicht da.\n\nSätze und Besteuerungsarten unterscheiden sich je nach Land und Umsatzhöhe. Diesen Teil kläre mit einer Steuerberatung: Es ist eine der wenigen Beratungen, die sich von selbst bezahlt macht.",
      it: "Due imposte confondono quasi tutti, e confonderle costa caro:\n\n**L'IVA non è tua.** Quando incassi 116 per qualcosa che costa 100, quei 16 sono dello Stato: li stai solo custodendo. L'errore classico è spendere quel denaro perché è sul conto, e poi non averlo alla scadenza. Trattalo come denaro altrui dal primo giorno.\n\n**Le imposte sul reddito escono invece dal tuo utile.** Si calcolano su quanto hai guadagnato, non su quanto hai venduto. Ecco perché conservare le fatture d'acquisto conta tanto: ogni spesa legittima dimostrabile abbassa la base imponibile.\n\nLa regola pratica: metti da parte una percentuale fissa di ogni vendita su un conto separato, lo stesso giorno. Se non la separi quando entra, non ci sarà quando esce.\n\nAliquote e regimi cambiano per paese e per livello di ricavi. Quella parte verificala con un commercialista: è una delle poche consulenze che si ripaga da sola.",
      zh: "有两种税几乎让所有人都搞混，而搞混的代价很大：\n\n**增值税不是你的钱。** 一件成本价 100 的东西你收 116，那 16 属于税务局：你只是暂时保管。经典的错误是因为钱在账户里就花掉，等到申报时拿不出来。从第一天起就把它当成别人的钱。\n\n**所得税才是从你的利润里出的。** 它按你赚了多少算，不是按你卖了多少算。所以保留进货凭证特别重要：每一笔能证明的合法支出，都会降低计税的基数。\n\n实用做法：每笔销售当天就把固定比例转到另一个账户。进账时不留出来，出账时就不会有。\n\n税率和征收方式因国家和收入水平而异——在墨西哥，小生意用「简易信任制」比一般制度便宜得多。这部分务必找会计确认：这是少数几件「花钱咨询能自己赚回来」的事。",
    },
  },
  {
    id: "factura_cfdi",
    titulo: { es: "Facturar: qué es y cuándo hace falta", en: "Invoicing: what it is and when you need it", pt: "Nota fiscal: o que é e quando precisa", fr: "Facturer : quoi et quand", de: "Rechnungen: was und wann", it: "Fatturare: cos'è e quando serve", zh: "开发票：是什么、什么时候需要" },
    relacionados: ["impuestos_basicos", "cliente_nuevo_vs_recurrente"],
    palabras: ["factura", "facturar", "cfdi", "nota fiscal", "comprobante fiscal", "me piden factura", "como facturo", "invoice", "billing", "rechnung", "fattura", "发票"],
    respuesta: {
      es: "Una factura no es un recibo bonito: es el documento con el que tu cliente puede **descontar esa compra de sus propios impuestos**. Por eso te la piden, y por eso a veces te la piden después.\n\nLo que conviene tener claro:\n\n• **Si tu cliente es un negocio, casi siempre va a pedir factura.** Si vendes a empresas y no puedes facturar, te van a comprar a otro. Es de las razones más comunes por las que un negocio chico se queda sin clientes grandes.\n• **El precio con y sin factura no debería ser distinto.** Si cobras más \"con factura\", lo que estás diciendo es que el precio de siempre no incluía el impuesto — y ese hueco lo acabas pagando tú.\n• **Emítela en el momento, no después.** Reunir facturas de hace tres meses es de las tareas más ingratas que existen, y en muchos países ya no se puede.\n\nEn México el documento se llama CFDI y se timbra en línea; necesitas RFC, e.firma y un proveedor de facturación (hay gratuitos). Los detalles cambian seguido, así que confirma el procedimiento vigente antes de montarlo.",
      en: "An invoice isn't a fancy receipt: it's the document that lets your customer **deduct that purchase from their own taxes**. That's why they ask for one, and why they sometimes ask afterwards.\n\nWorth being clear on:\n\n• **If your customer is a business, they'll almost always want an invoice.** If you sell to companies and can't invoice, they'll buy elsewhere. It's one of the most common reasons a small business loses its bigger customers.\n• **The price with and without an invoice shouldn't differ.** If you charge more \"with invoice\", what you're saying is that your usual price didn't include tax — and you end up covering that gap yourself.\n• **Issue it on the spot, not later.** Chasing three-month-old invoices is one of the most thankless jobs there is, and in many countries it's no longer allowed.\n\nIn Mexico the document is called a CFDI and is stamped online; you need an RFC, an e.firma and an invoicing provider (there are free ones). The details change often, so confirm the current procedure before setting it up.",
      pt: "Uma nota fiscal não é um recibo bonito: é o documento com que seu cliente pode **abater aquela compra dos próprios impostos**. Por isso pedem, e por isso às vezes pedem depois.\n\nO que convém ter claro:\n\n• **Se seu cliente é uma empresa, quase sempre vai pedir nota.** Se vende para empresas e não consegue emitir, vão comprar de outro. É uma das razões mais comuns de um negócio pequeno perder clientes grandes.\n• **O preço com e sem nota não deveria ser diferente.** Se cobra mais \"com nota\", está dizendo que o preço de sempre não incluía o imposto — e esse buraco acaba saindo do seu bolso.\n• **Emita na hora, não depois.** Juntar notas de três meses atrás é das tarefas mais ingratas que existem, e em muitos lugares já nem é permitido.\n\nOs detalhes mudam com frequência e por país, então confirme o procedimento vigente antes de montar o processo.",
      fr: "Une facture n'est pas un joli reçu : c'est le document qui permet à votre client de **déduire cet achat de ses propres impôts**. C'est pour ça qu'on vous en demande une, parfois après coup.\n\nÀ garder en tête :\n\n• **Si votre client est une entreprise, il en voudra presque toujours une.** Si vous vendez aux sociétés sans pouvoir facturer, elles achèteront ailleurs. C'est l'une des raisons les plus fréquentes de perdre ses gros clients.\n• **Le prix avec et sans facture ne devrait pas différer.** Facturer plus « avec facture », c'est admettre que votre prix habituel n'incluait pas la taxe — et ce trou, vous finissez par le payer.\n• **Émettez-la sur le moment, pas après.** Courir après des factures de trois mois est l'une des tâches les plus ingrates qui soient, et c'est parfois devenu impossible.\n\nLes détails changent souvent et selon le pays : confirmez la procédure en vigueur avant de mettre le processus en place.",
      de: "Eine Rechnung ist kein hübscher Kassenzettel: Sie ist das Dokument, mit dem deine Kundschaft diesen Einkauf **von der eigenen Steuer absetzen** kann. Deshalb wird danach gefragt, manchmal auch im Nachhinein.\n\nWas klar sein sollte:\n\n• **Ist deine Kundschaft ein Betrieb, will sie fast immer eine Rechnung.** Wer an Firmen verkauft und nicht abrechnen kann, verliert sie an andere. Das ist einer der häufigsten Gründe, warum ein kleiner Betrieb große Kunden verliert.\n• **Der Preis mit und ohne Rechnung sollte gleich sein.** Wer „mit Rechnung\" mehr verlangt, sagt damit, dass der übliche Preis die Steuer nicht enthielt — und diese Lücke zahlst am Ende du.\n• **Stell sie sofort aus, nicht später.** Rechnungen von vor drei Monaten nachzupflegen ist eine der undankbarsten Aufgaben überhaupt und vielerorts gar nicht mehr zulässig.\n\nDie Details ändern sich oft und je nach Land — prüfe das aktuelle Verfahren, bevor du den Ablauf aufsetzt.",
      it: "Una fattura non è una ricevuta elegante: è il documento con cui il tuo cliente può **scaricare quell'acquisto dalle proprie imposte**. Per questo te la chiedono, e per questo a volte te la chiedono dopo.\n\nDa avere chiaro:\n\n• **Se il cliente è un'azienda, la vorrà quasi sempre.** Se vendi ad aziende e non puoi fatturare, compreranno altrove. È uno dei motivi più comuni per cui una piccola attività perde i clienti grandi.\n• **Il prezzo con e senza fattura non dovrebbe cambiare.** Se chiedi di più \"con fattura\", stai dicendo che il prezzo abituale non comprendeva l'imposta — e quel buco finisci per pagarlo tu.\n• **Emettila subito, non dopo.** Rincorrere fatture di tre mesi fa è tra i lavori più ingrati che esistano, e in molti paesi non è più permesso.\n\nI dettagli cambiano spesso e per paese: verifica la procedura in vigore prima di impostare il processo.",
      zh: "发票不是一张好看的收据：它是让客户能**把这笔采购从自己的税里抵扣掉**的凭证。所以他们要发票，有时事后才来要。\n\n需要弄清楚的：\n\n• **如果客户是企业，几乎一定会要发票。** 做企业生意却开不了票，他们会去别家买。这是小生意丢掉大客户最常见的原因之一。\n• **开票和不开票的价格不应该不一样。** 如果「开票要加钱」，等于承认你平时的报价没含税——这个缺口最后是你自己补。\n• **当场开，不要拖。** 补三个月前的发票是最吃力不讨好的活儿，而且很多国家已经不允许了。\n\n在墨西哥这个凭证叫 CFDI，需在线签章；要有 RFC、电子签名和开票服务商（有免费的）。细节经常变，动手前先确认现行流程。",
    },
  },
  {
    id: "tarjeta_credito_intereses",
    titulo: { es: "Tarjetas de crédito e intereses", en: "Credit cards and interest", pt: "Cartão de crédito e juros", fr: "Cartes de crédit et intérêts", de: "Kreditkarten und Zinsen", it: "Carte di credito e interessi", zh: "信用卡和利息" },
    relacionados: ["prestamos_intereses", "flujo_caja", "fondo_emergencia"],
    palabras: ["tarjeta de credito", "tarjeta", "intereses de la tarjeta", "pago minimo", "meses sin intereses", "deuda de tarjeta", "credit card", "interest", "cartao de credito", "carte de credit", "kreditkarte", "carta di credito", "信用卡"],
    respuesta: {
      es: "Una tarjeta de crédito es la herramienta más cara que existe si la usas mal, y gratis si la usas bien. La diferencia está en una sola cosa: **pagar el total antes de la fecha límite.**\n\nLo que casi nadie te explica:\n\n• **El pago mínimo está diseñado para que nunca termines.** Es la cantidad exacta que mantiene la deuda viva el mayor tiempo posible. Pagando solo el mínimo, una deuda mediana puede tardar años y costar más del doble.\n• **Los intereses se anuncian al mes, no al año.** Un \"4% mensual\" suena poco y es cerca de 60% anual. Compáralo siempre contra el costo anual, no el mensual.\n• **\"Meses sin intereses\" no siempre es sin costo.** A veces el precio de contado es más bajo. Pregunta cuánto cuesta pagando de una vez antes de aceptar los meses.\n• **La fecha de corte no es la fecha límite de pago.** Comprar justo después del corte te da casi el doble de días para pagar sin intereses.\n\nPara un negocio: usarla como colchón de flujo de caja durante unos días está bien. Usarla para financiar mercancía que se vende lento es la forma más rápida de que la deuda crezca más rápido que las ventas.",
      en: "A credit card is the most expensive tool there is if you use it badly, and free if you use it well. The difference comes down to one thing: **paying the full balance before the due date.**\n\nWhat almost nobody explains:\n\n• **The minimum payment is designed so you never finish.** It's the exact amount that keeps the debt alive as long as possible. Paying only the minimum, a mid-sized debt can take years and cost more than double.\n• **Interest is advertised monthly, not annually.** \"4% a month\" sounds small and is close to 60% a year. Always compare the annual cost, not the monthly one.\n• **\"Interest-free instalments\" aren't always free.** Sometimes the cash price is lower. Ask what it costs paid in full before accepting the plan.\n• **The statement date isn't the payment deadline.** Buying just after the statement closes gives you almost twice as many interest-free days.\n\nFor a business: using it as a cash-flow cushion for a few days is fine. Using it to finance slow-moving stock is the fastest way to make the debt grow faster than the sales.",
      pt: "Um cartão de crédito é a ferramenta mais cara que existe se você usa mal, e gratuita se usa bem. A diferença está numa coisa só: **pagar o total antes do vencimento.**\n\nO que quase ninguém explica:\n\n• **O pagamento mínimo foi desenhado para você nunca terminar.** É a quantia exata que mantém a dívida viva o máximo de tempo. Pagando só o mínimo, uma dívida média pode levar anos e custar mais que o dobro.\n• **Os juros são anunciados ao mês, não ao ano.** \"4% ao mês\" parece pouco e dá quase 60% ao ano. Compare sempre pelo custo anual.\n• **\"Parcelado sem juros\" nem sempre é sem custo.** Às vezes o preço à vista é menor. Pergunte quanto custa pagando de uma vez antes de aceitar as parcelas.\n• **A data de fechamento não é a data de vencimento.** Comprar logo depois do fechamento dá quase o dobro de dias sem juros.\n\nPara um negócio: usar como colchão de caixa por alguns dias tudo bem. Usar para financiar mercadoria que gira devagar é o jeito mais rápido de a dívida crescer mais que as vendas.",
      fr: "Une carte de crédit est l'outil le plus cher qui soit si on l'utilise mal, et gratuit si on l'utilise bien. Tout tient à une chose : **payer la totalité avant l'échéance.**\n\nCe que presque personne n'explique :\n\n• **Le paiement minimum est conçu pour que vous ne finissiez jamais.** C'est le montant exact qui maintient la dette en vie le plus longtemps possible. Au minimum seul, une dette moyenne peut durer des années et coûter plus du double.\n• **Les intérêts sont annoncés au mois, pas à l'année.** « 4 % par mois » paraît peu et fait près de 60 % par an. Comparez toujours le coût annuel.\n• **Le « sans frais » n'est pas toujours sans coût.** Le prix comptant est parfois plus bas. Demandez le prix en une fois avant d'accepter l'échelonnement.\n• **La date d'arrêté n'est pas la date limite de paiement.** Acheter juste après l'arrêté double presque le délai sans intérêts.\n\nPour une entreprise : s'en servir comme tampon de trésorerie quelques jours, très bien. S'en servir pour financer du stock qui tourne lentement, c'est le moyen le plus rapide de faire grossir la dette plus vite que les ventes.",
      de: "Eine Kreditkarte ist das teuerste Werkzeug überhaupt, wenn man sie falsch nutzt, und kostenlos, wenn man sie richtig nutzt. Der Unterschied liegt an einer einzigen Sache: **den vollen Betrag vor dem Fälligkeitstag zahlen.**\n\nWas fast niemand erklärt:\n\n• **Die Mindestrate ist so gebaut, dass du nie fertig wirst.** Sie ist genau der Betrag, der die Schuld möglichst lange am Leben hält. Nur mit der Mindestrate kann eine mittlere Schuld Jahre dauern und mehr als das Doppelte kosten.\n• **Zinsen werden pro Monat beworben, nicht pro Jahr.** „4 % monatlich\" klingt wenig und sind fast 60 % im Jahr. Vergleiche immer die Jahreskosten.\n• **„Zinsfreie Raten\" sind nicht immer kostenlos.** Manchmal ist der Barpreis niedriger. Frag nach dem Preis bei Sofortzahlung, bevor du Raten zusagst.\n• **Der Abrechnungstag ist nicht der Zahltag.** Direkt nach dem Abschluss zu kaufen verschafft dir fast doppelt so viele zinsfreie Tage.\n\nFür einen Betrieb: als Liquiditätspuffer für ein paar Tage ist sie in Ordnung. Um langsam drehende Ware zu finanzieren, ist sie der schnellste Weg, die Schuld schneller wachsen zu lassen als den Umsatz.",
      it: "Una carta di credito è lo strumento più caro che esista se la usi male, e gratuito se la usi bene. La differenza sta in una cosa sola: **pagare il totale prima della scadenza.**\n\nQuello che quasi nessuno spiega:\n\n• **Il pagamento minimo è progettato perché tu non finisca mai.** È la cifra esatta che tiene in vita il debito il più a lungo possibile. Pagando solo il minimo, un debito medio può durare anni e costare più del doppio.\n• **Gli interessi si pubblicizzano al mese, non all'anno.** \"4% al mese\" sembra poco ed è quasi il 60% annuo. Confronta sempre il costo annuo.\n• **Le \"rate senza interessi\" non sono sempre senza costo.** A volte il prezzo in contanti è più basso. Chiedi quanto costa pagando in un'unica soluzione prima di accettare le rate.\n• **La data di chiusura non è la scadenza di pagamento.** Comprare subito dopo la chiusura ti dà quasi il doppio dei giorni senza interessi.\n\nPer un'attività: usarla come cuscinetto di cassa per qualche giorno va bene. Usarla per finanziare merce che gira lenta è il modo più rapido di far crescere il debito più delle vendite.",
      zh: "信用卡用错了是世界上最贵的工具，用对了完全免费。区别只在一件事：**在到期日前还清全额。**\n\n几乎没人告诉你的：\n\n• **最低还款额的设计目的就是让你永远还不完。** 它恰好是让债务活得最久的那个数。只还最低额，一笔中等的欠款可能要还好几年，总成本超过一倍。\n• **利率按月宣传，不按年。** 「月息 4%」听着不多，年化接近 60%。永远按年化成本去比较。\n• **「免息分期」不一定没有成本。** 有时一次性付款的价格更低。答应分期前，先问一次付清多少钱。\n• **账单日不是还款日。** 在账单日刚过后消费，免息天数几乎翻倍。\n\n对生意来说：拿它当几天的现金流缓冲没问题。拿它去压周转慢的货，是让债务涨得比销售还快的最快方式。",
    },
  },
  {
    id: "fondo_emergencia",
    titulo: { es: "Fondo de emergencia del negocio", en: "Business emergency fund", pt: "Fundo de emergência do negócio", fr: "Fonds d'urgence de l'entreprise", de: "Notgroschen für den Betrieb", it: "Fondo di emergenza dell'attività", zh: "生意的应急金" },
    relacionados: ["flujo_caja", "capital_trabajo", "babilonia"],
    palabras: ["fondo de emergencia", "colchon", "ahorro del negocio", "guardar dinero", "cuanto debo ahorrar", "reserva", "emergency fund", "savings", "reserva de emergencia", "fonds d urgence", "notgroschen", "fondo di emergenza", "应急"],
    respuesta: {
      es: "Casi ningún negocio chico cierra por una mala decisión. Cierran por **un mes malo que llegó sin colchón.**\n\nLa meta razonable: **de 3 a 6 meses de tus gastos fijos.** No de tus ventas — de lo que tienes que pagar aunque no vendas nada: renta, sueldos, luz, internet, tu propio sueldo mínimo para vivir.\n\nCómo llegar sin que duela:\n\n• Calcula tus gastos fijos de un mes. Ese es tu \"1 mes\".\n• Aparta un porcentaje fijo de cada venta —aunque sea 5%— el mismo día que entra.\n• Ponlo en una cuenta distinta, idealmente en otro banco. La fricción de moverlo es lo que evita que te lo gastes.\n• No lo toques para oportunidades. Una oferta del proveedor no es una emergencia.\n\nQué sí es emergencia: se descompuso el refrigerador que sostiene tu mercancía, un mes de ventas se cayó a la mitad, un cliente grande no pagó. Para eso existe.\n\nSi ahora mismo no tienes nada, empieza con la meta de **un solo mes**. Ese primer mes cambia por completo la forma en que tomas decisiones, porque dejas de negociar con miedo.",
      en: "Almost no small business closes because of one bad decision. They close because of **one bad month that arrived without a cushion.**\n\nA sensible target: **3 to 6 months of your fixed costs.** Not of your sales — of what you must pay even if you sell nothing: rent, wages, power, internet, your own minimum living wage.\n\nHow to get there without it hurting:\n\n• Work out one month of fixed costs. That's your \"1 month\".\n• Set aside a fixed percentage of every sale — even 5% — the same day it comes in.\n• Keep it in a different account, ideally at another bank. The friction of moving it is what stops you spending it.\n• Don't touch it for opportunities. A supplier's deal is not an emergency.\n\nWhat is an emergency: the fridge holding your stock broke, a month's sales halved, a big customer didn't pay. That's what it's for.\n\nIf you have nothing right now, aim for **one single month**. That first month completely changes how you make decisions, because you stop negotiating from fear.",
      pt: "Quase nenhum negócio pequeno fecha por uma decisão ruim. Fecham por **um mês ruim que chegou sem colchão.**\n\nA meta razoável: **de 3 a 6 meses dos seus gastos fixos.** Não das vendas — do que você tem que pagar mesmo sem vender nada: aluguel, salários, luz, internet, seu próprio mínimo para viver.\n\nComo chegar lá sem doer:\n\n• Calcule seus gastos fixos de um mês. Esse é seu \"1 mês\".\n• Separe um percentual fixo de cada venda — nem que sejam 5% — no mesmo dia em que entra.\n• Coloque numa conta diferente, de preferência em outro banco. O atrito de mover é o que impede de gastar.\n• Não use para oportunidades. Uma oferta do fornecedor não é emergência.\n\nO que é emergência: quebrou a geladeira que segura sua mercadoria, as vendas do mês caíram pela metade, um cliente grande não pagou. É para isso.\n\nSe hoje você não tem nada, mire em **um único mês**. Esse primeiro mês muda completamente como você decide, porque para de negociar com medo.",
      fr: "Presque aucune petite entreprise ne ferme à cause d'une mauvaise décision. Elles ferment à cause d'**un mauvais mois arrivé sans matelas.**\n\nObjectif raisonnable : **3 à 6 mois de charges fixes.** Pas de chiffre d'affaires — de ce qu'il faut payer même sans rien vendre : loyer, salaires, électricité, internet, votre propre minimum vital.\n\nComment y arriver sans douleur :\n\n• Calculez un mois de charges fixes. C'est votre « 1 mois ».\n• Mettez de côté un pourcentage fixe de chaque vente — même 5 % — le jour même.\n• Sur un compte différent, idéalement dans une autre banque. C'est la friction qui vous empêche de le dépenser.\n• N'y touchez pas pour des opportunités. Une promo fournisseur n'est pas une urgence.\n\nCe qui est une urgence : le frigo qui tient votre marchandise a lâché, les ventes du mois ont chuté de moitié, un gros client n'a pas payé. C'est fait pour ça.\n\nSi vous n'avez rien aujourd'hui, visez **un seul mois**. Ce premier mois change complètement votre façon de décider, parce que vous cessez de négocier avec la peur.",
      de: "Fast kein kleiner Betrieb schließt wegen einer falschen Entscheidung. Sie schließen wegen **eines schlechten Monats ohne Polster.**\n\nSinnvolles Ziel: **3 bis 6 Monate deiner Fixkosten.** Nicht deines Umsatzes — dessen, was du zahlen musst, auch wenn du nichts verkaufst: Miete, Löhne, Strom, Internet, dein eigenes Existenzminimum.\n\nWie du hinkommst, ohne dass es wehtut:\n\n• Rechne einen Monat Fixkosten aus. Das ist dein „1 Monat\".\n• Leg von jedem Verkauf einen festen Prozentsatz zurück — und seien es 5 % — noch am selben Tag.\n• Auf ein anderes Konto, am besten bei einer anderen Bank. Genau diese Hürde hält dich davon ab, es auszugeben.\n• Rühr es nicht für Gelegenheiten an. Ein Lieferantenangebot ist kein Notfall.\n\nWas ein Notfall ist: Der Kühlschrank mit deiner Ware ist kaputt, der Monatsumsatz hat sich halbiert, ein großer Kunde hat nicht gezahlt. Dafür ist es da.\n\nWenn du gerade gar nichts hast, ziele auf **einen einzigen Monat**. Dieser erste Monat verändert dein Entscheiden vollständig, weil du aufhörst, aus Angst zu verhandeln.",
      it: "Quasi nessuna piccola attività chiude per una decisione sbagliata. Chiudono per **un mese storto arrivato senza cuscinetto.**\n\nObiettivo ragionevole: **da 3 a 6 mesi delle tue spese fisse.** Non delle vendite — di quello che devi pagare anche se non vendi niente: affitto, stipendi, luce, internet, il tuo minimo per vivere.\n\nCome arrivarci senza soffrire:\n\n• Calcola un mese di spese fisse. Quello è il tuo \"1 mese\".\n• Metti da parte una percentuale fissa di ogni vendita — anche il 5% — lo stesso giorno in cui entra.\n• Su un conto diverso, meglio se in un'altra banca. È l'attrito a impedirti di spenderlo.\n• Non toccarlo per le occasioni. Un'offerta del fornitore non è un'emergenza.\n\nCos'è un'emergenza: si è rotto il frigo che tiene la merce, le vendite del mese si sono dimezzate, un cliente grosso non ha pagato. È per questo che esiste.\n\nSe oggi non hai nulla, punta a **un solo mese**. Quel primo mese cambia completamente il modo in cui decidi, perché smetti di trattare con la paura addosso.",
      zh: "几乎没有哪家小生意是因为一个错误决定倒掉的。它们倒在**一个没有缓冲垫的淡月上。**\n\n合理目标：**3 到 6 个月的固定支出。** 不是销售额——是就算一件都卖不出去也必须付的钱：房租、工资、水电、网费，还有你自己维持生活的最低收入。\n\n怎么攒才不痛苦：\n\n• 算出一个月的固定支出。那就是你的「1 个月」。\n• 每笔销售当天留出固定比例——哪怕只有 5%。\n• 放在另一个账户，最好是另一家银行。挪动的麻烦，正是让你不去花它的原因。\n• 不要为了「机会」动它。供应商的促销不算紧急。\n\n什么才算紧急：存货的冰柜坏了、当月销售腰斩、大客户没付款。它就是为这些准备的。\n\n如果现在一分都没有，先以**一个月**为目标。这第一个月会彻底改变你做决定的方式，因为你不再带着恐惧去谈判。",
    },
  },
  {
    id: "seguridad_digital",
    titulo: { es: "Contraseñas, fraudes y seguridad digital", en: "Passwords, scams and digital security", pt: "Senhas, golpes e segurança digital", fr: "Mots de passe, arnaques et sécurité", de: "Passwörter, Betrug und digitale Sicherheit", it: "Password, truffe e sicurezza digitale", zh: "密码、诈骗与网络安全" },
    relacionados: ["robo_hormiga", "pagos_digitales"],
    palabras: ["contrasena", "password", "me hackearon", "fraude", "estafa", "phishing", "seguridad", "virus", "me robaron la cuenta", "correo sospechoso", "scam", "senha", "mot de passe", "passwort", "truffa", "密码", "诈骗"],
    respuesta: {
      es: "Casi ningún fraude a un negocio chico es un hacker con capucha. Son tres cosas mucho más aburridas:\n\n**1. La misma contraseña en todos lados.** Cuando se filtra un sitio cualquiera, prueban ese correo y contraseña en el banco. Funciona sorprendentemente seguido. Usa una distinta al menos para: correo, banco y el sistema de tu negocio.\n\n**2. Un mensaje que te apura.** \"Tu cuenta será bloqueada hoy\", \"confirma tus datos\", \"soy tu proveedor, cambiamos de cuenta bancaria\". La prisa es la herramienta, no la tecnología. **Regla: ningún banco, ninguna plataforma y ningún proveedor real te pide datos por mensaje.** Si dudas, cuelga y llama tú al número que ya tenías.\n\n**3. Nadie más tiene tu contraseña... excepto que sí.** Si tus empleados entran con tu usuario, no tienes forma de saber quién hizo qué. Dale a cada persona su propio acceso — en CoreStock puedes crear miembros del equipo con permisos distintos.\n\nDos cosas que valen más que todo lo demás: **activa la verificación en dos pasos** en tu correo y tu banco, y **verifica los cambios de cuenta bancaria por teléfono**, siempre. El fraude del \"cambiamos de cuenta\" es el que más dinero se lleva de negocios pequeños.",
      en: "Almost no fraud against a small business involves a hacker in a hoodie. It's three much duller things:\n\n**1. The same password everywhere.** When some random site leaks, they try that email and password at your bank. It works surprisingly often. Use a different one for at least: email, bank, and your business system.\n\n**2. A message that rushes you.** \"Your account will be blocked today\", \"confirm your details\", \"it's your supplier, we changed bank accounts\". Urgency is the tool, not technology. **Rule: no real bank, platform or supplier asks for details by message.** If in doubt, hang up and call the number you already had.\n\n**3. Nobody else has your password... except they do.** If your staff log in as you, you have no way of knowing who did what. Give each person their own access — in CoreStock you can create team members with different permissions.\n\nTwo things worth more than everything else: **turn on two-step verification** on your email and your bank, and **verify bank account changes by phone**, every time. The \"we changed accounts\" scam takes more money from small businesses than any other.",
      pt: "Quase nenhuma fraude contra um negócio pequeno envolve um hacker de capuz. São três coisas bem mais chatas:\n\n**1. A mesma senha em todo lugar.** Quando vaza um site qualquer, testam aquele e-mail e senha no banco. Funciona com uma frequência assustadora. Use uma diferente pelo menos para: e-mail, banco e o sistema do seu negócio.\n\n**2. Uma mensagem que te apressa.** \"Sua conta será bloqueada hoje\", \"confirme seus dados\", \"sou seu fornecedor, mudamos de conta bancária\". A pressa é a ferramenta, não a tecnologia. **Regra: nenhum banco, plataforma ou fornecedor de verdade pede dados por mensagem.** Na dúvida, desligue e ligue você para o número que já tinha.\n\n**3. Ninguém mais tem sua senha... só que tem.** Se seus funcionários entram com o seu usuário, não há como saber quem fez o quê. Dê a cada pessoa o próprio acesso — no CoreStock você pode criar membros da equipe com permissões diferentes.\n\nDuas coisas que valem mais que todo o resto: **ative a verificação em duas etapas** no e-mail e no banco, e **confirme mudanças de conta bancária por telefone**, sempre. O golpe do \"mudamos de conta\" é o que mais leva dinheiro de negócios pequenos.",
      fr: "Presque aucune fraude contre une petite entreprise n'implique un pirate à capuche. Ce sont trois choses bien plus ennuyeuses :\n\n**1. Le même mot de passe partout.** Quand un site quelconque fuit, on essaie cet e-mail et ce mot de passe à la banque. Ça marche étonnamment souvent. Utilisez-en un différent au moins pour : e-mail, banque et système de gestion.\n\n**2. Un message qui vous presse.** « Votre compte sera bloqué aujourd'hui », « confirmez vos données », « c'est votre fournisseur, on a changé de compte bancaire ». L'urgence est l'outil, pas la technologie. **Règle : aucune banque, plateforme ou fournisseur réel ne demande de données par message.** Dans le doute, raccrochez et appelez le numéro que vous aviez déjà.\n\n**3. Personne d'autre n'a votre mot de passe… sauf que si.** Si vos employés se connectent avec votre compte, impossible de savoir qui a fait quoi. Donnez à chacun son accès — dans CoreStock, vous pouvez créer des membres avec des permissions différentes.\n\nDeux choses qui valent plus que tout : **activez la validation en deux étapes** sur votre e-mail et votre banque, et **vérifiez tout changement de compte bancaire par téléphone**, systématiquement. L'arnaque au « changement de compte » est celle qui coûte le plus cher aux petites entreprises.",
      de: "Fast kein Betrug an einem kleinen Betrieb hat mit einem Hacker im Kapuzenpulli zu tun. Es sind drei viel langweiligere Dinge:\n\n**1. Überall dasselbe Passwort.** Wenn irgendeine Seite geleakt wird, probiert man diese E-Mail samt Passwort bei der Bank. Das klappt erstaunlich oft. Nimm mindestens für E-Mail, Bank und dein Betriebssystem je ein eigenes.\n\n**2. Eine Nachricht, die dich hetzt.** „Ihr Konto wird heute gesperrt\", „bestätigen Sie Ihre Daten\", „hier Ihr Lieferant, wir haben die Bankverbindung geändert\". Das Werkzeug ist die Eile, nicht die Technik. **Regel: Keine echte Bank, Plattform oder Lieferfirma fragt per Nachricht nach Daten.** Im Zweifel auflegen und selbst die Nummer anrufen, die du schon hattest.\n\n**3. Niemand sonst kennt dein Passwort … doch, tut er.** Wenn deine Leute sich mit deinem Zugang anmelden, weißt du nie, wer was getan hat. Gib jeder Person einen eigenen Zugang — in CoreStock kannst du Teammitglieder mit unterschiedlichen Rechten anlegen.\n\nZwei Dinge, die mehr wert sind als alles andere: **Zwei-Faktor-Bestätigung** für E-Mail und Bank aktivieren und **Änderungen der Bankverbindung immer telefonisch prüfen**. Der „Wir haben das Konto gewechselt\"-Betrug holt aus kleinen Betrieben das meiste Geld.",
      it: "Quasi nessuna truffa a una piccola attività coinvolge un hacker col cappuccio. Sono tre cose molto più noiose:\n\n**1. La stessa password ovunque.** Quando un sito qualsiasi subisce una fuga, provano quella email e password in banca. Funziona sorprendentemente spesso. Usane una diversa almeno per: email, banca e gestionale.\n\n**2. Un messaggio che ti mette fretta.** \"Il suo conto sarà bloccato oggi\", \"confermi i dati\", \"sono il suo fornitore, abbiamo cambiato conto\". Lo strumento è la fretta, non la tecnologia. **Regola: nessuna banca, piattaforma o fornitore vero chiede dati via messaggio.** Nel dubbio, riattacca e chiama tu il numero che avevi già.\n\n**3. Nessun altro ha la tua password… invece sì.** Se i dipendenti entrano col tuo utente, non c'è modo di sapere chi ha fatto cosa. Dai a ognuno il proprio accesso — in CoreStock puoi creare membri del team con permessi diversi.\n\nDue cose che valgono più di tutto il resto: **attiva la verifica in due passaggi** su email e banca, e **verifica sempre per telefono i cambi di conto bancario**. La truffa del \"abbiamo cambiato conto\" è quella che porta via più soldi alle piccole attività.",
      zh: "针对小生意的诈骗，几乎没有一起是穿连帽衫的黑客干的。都是三件无聊得多的事：\n\n**1. 到处用同一个密码。** 某个网站一泄露，骗子就拿那组邮箱和密码去试你的网银。成功率高得吓人。至少让邮箱、银行、生意系统各用一个不同的密码。\n\n**2. 一条催你的消息。** 「您的账户今日将被冻结」「请确认资料」「我是你的供应商，我们换银行账号了」。工具是「急」，不是技术。**规则：真正的银行、平台、供应商都不会用消息问你要资料。** 有疑问就挂断，用你原来就有的号码打回去。\n\n**3. 没别人知道你的密码……其实有。** 如果员工用你的账号登录，你根本无从得知谁做了什么。给每个人独立的账号——在 CoreStock 里可以创建权限不同的团队成员。\n\n两件比其他所有都重要的事：给邮箱和网银**开启两步验证**，以及**任何银行账号变更都用电话核实**，每次都要。「我们换账号了」这种骗局，从小生意手里骗走的钱最多。",
    },
  },
  {
    id: "pagos_digitales",
    titulo: { es: "Cobrar con terminal, transferencia o QR", en: "Card terminals, transfers and QR payments", pt: "Maquininha, transferência e QR", fr: "Terminal, virement et paiement QR", de: "Kartenlesegerät, Überweisung und QR", it: "POS, bonifico e pagamento QR", zh: "刷卡机、转账与二维码收款" },
    relacionados: ["seguridad_digital", "flujo_caja", "ticket_promedio"],
    palabras: ["terminal", "cobrar con tarjeta", "maquinita", "pago con tarjeta", "transferencia", "codi", "qr", "comision de la terminal", "aceptar tarjetas", "card terminal", "pos", "maquininha", "terminal de paiement", "kartenzahlung", "pagamenti digitali", "刷卡"],
    respuesta: {
      es: "La pregunta real no es \"¿acepto tarjetas?\" sino **\"¿cuánto me cuesta no aceptarlas?\"**.\n\nLo que hay que mirar antes de decidir:\n\n• **La comisión se come tu margen, no tu venta.** Si vendes con 20% de margen y la terminal cobra 3.5%, no perdiste 3.5% — perdiste casi la sexta parte de tu ganancia. En productos de margen bajo eso duele de verdad.\n• **Pero el ticket promedio sube.** Pagar con tarjeta duele menos que soltar billetes, y se nota: la gente compra más por visita. En la mayoría de los giros eso compensa la comisión con margen de sobra.\n• **Cuidado con cuándo te depositan.** Algunas terminales pagan al día siguiente, otras en 3 días o semanal. Si tu flujo de caja está apretado, esa diferencia importa más que medio punto de comisión.\n\n**Transferencia** suele ser lo más barato (a veces gratis) y cae al instante, pero depende de que el cliente traiga la app y sepa usarla. Sirve muy bien para tickets grandes, donde la comisión de tarjeta sí sería un golpe.\n\nUna advertencia práctica: **confirma que el dinero llegó a tu cuenta antes de entregar la mercancía.** Los comprobantes de transferencia se falsifican con una captura editada, y es de los fraudes más comunes en mostrador.",
      en: "The real question isn't \"should I accept cards?\" but **\"what does it cost me not to?\"**.\n\nWhat to look at before deciding:\n\n• **The fee eats your margin, not your sale.** If you sell at a 20% margin and the terminal charges 3.5%, you didn't lose 3.5% — you lost almost a sixth of your profit. On low-margin products that really hurts.\n• **But the average ticket goes up.** Paying by card hurts less than handing over notes, and it shows: people buy more per visit. In most trades that more than covers the fee.\n• **Watch when you actually get paid.** Some terminals settle next day, others in 3 days or weekly. If your cash flow is tight, that difference matters more than half a point of commission.\n\n**Bank transfer** is usually cheapest (sometimes free) and lands instantly, but it depends on the customer having the app and knowing how to use it. It works very well for large tickets, where a card fee would genuinely sting.\n\nOne practical warning: **confirm the money reached your account before handing over the goods.** Transfer receipts are faked with an edited screenshot, and it's one of the most common counter frauds there is.",
      pt: "A pergunta real não é \"aceito cartão?\" e sim **\"quanto me custa não aceitar?\"**.\n\nO que olhar antes de decidir:\n\n• **A taxa come sua margem, não sua venda.** Se vende com 20% de margem e a maquininha cobra 3,5%, você não perdeu 3,5% — perdeu quase um sexto do seu lucro. Em produtos de margem baixa isso dói de verdade.\n• **Mas o ticket médio sobe.** Pagar com cartão dói menos que soltar dinheiro, e isso aparece: as pessoas compram mais por visita. Na maioria dos ramos isso cobre a taxa com folga.\n• **Cuidado com quando cai o dinheiro.** Algumas maquininhas pagam no dia seguinte, outras em 3 dias ou semanal. Se seu caixa está apertado, essa diferença pesa mais que meio ponto de taxa.\n\n**Transferência** costuma ser o mais barato (às vezes grátis) e cai na hora, mas depende de o cliente ter o app e saber usar. Funciona muito bem para tickets grandes, onde a taxa do cartão seria um golpe.\n\nUm aviso prático: **confirme que o dinheiro caiu na sua conta antes de entregar a mercadoria.** Comprovantes de transferência são falsificados com um print editado, e é uma das fraudes mais comuns no balcão.",
      fr: "La vraie question n'est pas « dois-je accepter les cartes ? » mais **« combien me coûte de ne pas les accepter ? »**.\n\nÀ regarder avant de décider :\n\n• **La commission ronge votre marge, pas votre vente.** Avec 20 % de marge et un terminal à 3,5 %, vous n'avez pas perdu 3,5 % — vous avez perdu près d'un sixième de votre bénéfice. Sur des produits à faible marge, ça fait mal.\n• **Mais le panier moyen monte.** Payer par carte fait moins mal que sortir des billets, et ça se voit : les gens achètent plus par visite. Dans la plupart des métiers, cela couvre largement la commission.\n• **Attention à la date de versement.** Certains terminaux versent le lendemain, d'autres à 3 jours ou par semaine. Si votre trésorerie est tendue, cet écart compte plus qu'un demi-point de commission.\n\n**Le virement** est souvent le moins cher (parfois gratuit) et arrive instantanément, mais suppose que le client ait l'application. Idéal pour les gros paniers, où la commission carte piquerait vraiment.\n\nUn avertissement pratique : **vérifiez que l'argent est arrivé sur votre compte avant de remettre la marchandise.** Les justificatifs de virement se falsifient avec une capture retouchée : c'est l'une des fraudes de comptoir les plus courantes.",
      de: "Die eigentliche Frage ist nicht „soll ich Karten annehmen?\", sondern **„was kostet es mich, sie nicht anzunehmen?\"**.\n\nWorauf du vor der Entscheidung schaust:\n\n• **Die Gebühr frisst deine Marge, nicht deinen Umsatz.** Bei 20 % Marge und 3,5 % Gebühr hast du nicht 3,5 % verloren, sondern fast ein Sechstel deines Gewinns. Bei margenschwachen Produkten tut das richtig weh.\n• **Aber der Durchschnittsbon steigt.** Mit Karte zu zahlen tut weniger weh als Scheine hinzulegen, und das zeigt sich: Die Leute kaufen pro Besuch mehr. In den meisten Branchen deckt das die Gebühr mit Abstand.\n• **Achte darauf, wann ausgezahlt wird.** Manche Geräte zahlen am nächsten Tag, andere nach 3 Tagen oder wöchentlich. Bei knapper Liquidität wiegt das schwerer als ein halber Prozentpunkt.\n\n**Überweisung** ist meist am günstigsten (manchmal gratis) und sofort da, setzt aber voraus, dass die Kundschaft die App hat. Für große Beträge ideal, wo die Kartengebühr wirklich schmerzt.\n\nEine praktische Warnung: **Prüfe, dass das Geld auf deinem Konto ist, bevor du die Ware herausgibst.** Überweisungsbelege werden mit einem bearbeiteten Screenshot gefälscht — einer der häufigsten Betrügereien am Tresen.",
      it: "La domanda vera non è \"accetto le carte?\" ma **\"quanto mi costa non accettarle?\"**.\n\nCosa guardare prima di decidere:\n\n• **La commissione mangia il margine, non la vendita.** Se vendi al 20% di margine e il POS prende il 3,5%, non hai perso il 3,5% — hai perso quasi un sesto dell'utile. Su prodotti a margine basso fa male davvero.\n• **Ma lo scontrino medio sale.** Pagare con carta fa meno male che tirare fuori banconote, e si vede: la gente compra di più per visita. Nella maggior parte dei settori questo copre la commissione con abbondanza.\n• **Attento a quando ti accreditano.** Alcuni POS pagano il giorno dopo, altri a 3 giorni o settimanalmente. Se la cassa è tirata, quella differenza pesa più di mezzo punto di commissione.\n\n**Il bonifico** di solito è il più economico (a volte gratis) e arriva subito, ma richiede che il cliente abbia l'app. Ottimo per importi alti, dove la commissione della carta sarebbe una botta.\n\nUn avviso pratico: **verifica che il denaro sia arrivato sul conto prima di consegnare la merce.** Le ricevute di bonifico si falsificano con uno screenshot ritoccato: è una delle truffe da bancone più comuni.",
      zh: "真正的问题不是「我要不要收卡？」，而是**「不收卡要付出多少代价？」**。\n\n决定前该看的：\n\n• **手续费吃掉的是你的毛利，不是营业额。** 如果毛利率 20%、刷卡机收 3.5%，你损失的不是 3.5%——是接近六分之一的利润。低毛利商品尤其肉疼。\n• **但客单价会上升。** 刷卡比掏现金「痛感」低，效果很明显：每次来店买得更多。多数行业里，这部分远超手续费。\n• **注意什么时候到账。** 有的次日结算，有的 3 天或按周。如果你现金流紧张，这个差别比半个点的费率重要得多。\n\n**银行转账**通常最便宜（有时免费）而且实时到账，但要看客户有没有 App、会不会用。大额交易特别合适，那种金额下刷卡手续费是真的疼。\n\n一个实用提醒：**确认钱到了你的账户再交货。** 转账凭证用修图就能伪造，这是柜台最常见的骗局之一。",
    },
  },
  {
    id: "criptomonedas",
    titulo: { es: "Criptomonedas: qué son y qué riesgo tienen", en: "Cryptocurrency: what it is and its risks", pt: "Criptomoedas: o que são e o risco", fr: "Cryptomonnaies : quoi et quels risques", de: "Kryptowährungen: was und welche Risiken", it: "Criptovalute: cosa sono e che rischi hanno", zh: "加密货币：是什么、有什么风险" },
    relacionados: ["riesgo_ruina", "roi", "inflacion"],
    palabras: ["cripto", "criptomonedas", "bitcoin", "ethereum", "invertir en cripto", "blockchain", "usdt", "crypto", "criptomoedas", "kryptowahrungen", "criptovalute", "加密货币", "比特币"],
    respuesta: {
      es: "Una criptomoneda es dinero digital que no depende de ningún banco central: las transacciones se registran en una base de datos pública y compartida (la blockchain), y nadie puede editarla hacia atrás.\n\nLo que es verdad de las dos partes:\n\n• **Sirve de verdad** para mover dinero entre países rápido y barato, y en países con inflación extrema o controles de cambio le ha resuelto la vida a mucha gente.\n• **Y es extremadamente volátil.** Caídas del 50% o más han pasado varias veces, en cuestión de meses. No es una anomalía del pasado; es cómo se comporta.\n• **No hay a quién reclamarle.** Si pierdes tus claves o te estafan, no existe un banco que reverse la operación. Esa es la contraparte directa de que no dependa de nadie.\n\nMi lectura honesta para un negocio: **el dinero de tu negocio no es dinero de riesgo.** Lo que necesitas para pagar proveedores, renta y sueldos el mes que viene no puede estar en algo que puede valer la mitad el mes que viene. Si te interesa, hazlo con dinero personal que puedas perder entero sin que cambie nada — y desconfía de cualquiera que te prometa rendimientos fijos, porque eso ya no es cripto, es el esquema de siempre con nombre nuevo.",
      en: "A cryptocurrency is digital money that doesn't depend on any central bank: transactions are recorded in a public shared database (the blockchain) that nobody can edit retroactively.\n\nWhat's true on both sides:\n\n• **It genuinely works** for moving money across borders fast and cheap, and in countries with extreme inflation or currency controls it has solved real problems for a lot of people.\n• **And it's extremely volatile.** Drops of 50% or more have happened several times, within months. That's not a past anomaly; that's how it behaves.\n• **There's nobody to complain to.** If you lose your keys or get scammed, no bank can reverse it. That's the direct flip side of not depending on anyone.\n\nMy honest read for a business: **your business's money is not risk money.** What you need to pay suppliers, rent and wages next month cannot sit in something that might be worth half next month. If it interests you, use personal money you could lose entirely without anything changing — and distrust anyone promising fixed returns, because that isn't crypto any more, it's the same old scheme with a new name.",
      pt: "Uma criptomoeda é dinheiro digital que não depende de nenhum banco central: as transações ficam registradas numa base de dados pública e compartilhada (a blockchain), que ninguém pode editar para trás.\n\nO que é verdade dos dois lados:\n\n• **Serve de verdade** para mover dinheiro entre países rápido e barato, e em países com inflação extrema ou controle cambial resolveu a vida de muita gente.\n• **E é extremamente volátil.** Quedas de 50% ou mais já aconteceram várias vezes, em questão de meses. Não é uma anomalia do passado; é como se comporta.\n• **Não há a quem reclamar.** Se você perde as chaves ou é golpeado, não existe banco que reverta. É a contrapartida direta de não depender de ninguém.\n\nMinha leitura honesta para um negócio: **o dinheiro do seu negócio não é dinheiro de risco.** O que você precisa para pagar fornecedores, aluguel e salários no mês que vem não pode estar em algo que pode valer metade no mês que vem. Se te interessa, use dinheiro pessoal que possa perder inteiro sem que nada mude — e desconfie de quem promete rendimento fixo, porque isso já não é cripto, é o esquema de sempre com nome novo.",
      fr: "Une cryptomonnaie est de la monnaie numérique qui ne dépend d'aucune banque centrale : les transactions sont inscrites dans une base publique et partagée (la blockchain) que personne ne peut réécrire.\n\nCe qui est vrai des deux côtés :\n\n• **Ça marche vraiment** pour déplacer de l'argent entre pays vite et pas cher, et dans les pays à inflation extrême ou contrôle des changes, cela a résolu de vrais problèmes.\n• **Et c'est extrêmement volatil.** Des chutes de 50 % ou plus se sont produites plusieurs fois, en quelques mois. Ce n'est pas une anomalie passée ; c'est son comportement.\n• **Il n'y a personne à qui se plaindre.** Clés perdues ou arnaque : aucune banque ne peut annuler. C'est la contrepartie directe de ne dépendre de personne.\n\nMon avis honnête pour une entreprise : **l'argent de votre entreprise n'est pas de l'argent à risque.** Ce qu'il vous faut le mois prochain pour les fournisseurs, le loyer et les salaires ne peut pas dormir dans quelque chose qui pourrait valoir moitié moins. Si le sujet vous intéresse, faites-le avec de l'argent personnel perdable en totalité — et méfiez-vous de quiconque promet des rendements fixes : ce n'est plus de la crypto, c'est le vieux schéma sous un nom neuf.",
      de: "Eine Kryptowährung ist digitales Geld, das von keiner Zentralbank abhängt: Transaktionen stehen in einer öffentlichen, geteilten Datenbank (der Blockchain), die niemand nachträglich ändern kann.\n\nWas auf beiden Seiten stimmt:\n\n• **Es funktioniert wirklich**, um Geld schnell und günstig über Grenzen zu bewegen; in Ländern mit extremer Inflation oder Devisenkontrollen hat es vielen Menschen echt geholfen.\n• **Und es ist extrem schwankend.** Einbrüche von 50 % und mehr gab es mehrfach, binnen Monaten. Das ist keine Anomalie der Vergangenheit, das ist sein Verhalten.\n• **Es gibt niemanden zum Reklamieren.** Wer die Schlüssel verliert oder betrogen wird, hat keine Bank, die etwas rückgängig macht. Das ist die direkte Kehrseite davon, von niemandem abzuhängen.\n\nMeine ehrliche Einschätzung für einen Betrieb: **Betriebsgeld ist kein Risikogeld.** Was du nächsten Monat für Lieferanten, Miete und Löhne brauchst, darf nicht in etwas liegen, das nächsten Monat die Hälfte wert sein kann. Wenn es dich interessiert, nimm privates Geld, dessen Totalverlust nichts ändert — und misstraue jedem, der feste Renditen verspricht: Das ist keine Krypto mehr, das ist das alte Schema unter neuem Namen.",
      it: "Una criptovaluta è denaro digitale che non dipende da nessuna banca centrale: le transazioni sono registrate in un database pubblico e condiviso (la blockchain) che nessuno può modificare a posteriori.\n\nCosa è vero da entrambe le parti:\n\n• **Serve davvero** per spostare denaro tra paesi in fretta e a poco prezzo, e in paesi con inflazione estrema o controlli sui cambi ha risolto problemi reali a molte persone.\n• **Ed è estremamente volatile.** Cali del 50% o più sono già successi più volte, nel giro di mesi. Non è un'anomalia del passato; è il suo comportamento.\n• **Non c'è nessuno a cui reclamare.** Se perdi le chiavi o ti truffano, nessuna banca annulla l'operazione. È il rovescio diretto del non dipendere da nessuno.\n\nLa mia lettura onesta per un'attività: **i soldi dell'attività non sono soldi di rischio.** Quello che ti serve il mese prossimo per fornitori, affitto e stipendi non può stare in qualcosa che il mese prossimo potrebbe valere la metà. Se ti interessa, usa denaro personale che puoi perdere per intero senza che cambi nulla — e diffida di chi promette rendimenti fissi, perché quella non è più cripto, è il solito schema con un nome nuovo.",
      zh: "加密货币是一种不依赖任何中央银行的数字货币：交易记录在一个公开共享的数据库（区块链）上，没人能事后改写。\n\n两边都成立的事实：\n\n• **它确实有用**：跨国转账又快又便宜；在通胀失控或有外汇管制的国家，它实实在在解决了很多人的问题。\n• **它也极度波动。** 几个月内跌掉 50% 以上发生过好几次。这不是过去的异常，这就是它的常态。\n• **出事没人可找。** 丢了私钥或者被骗，没有银行能帮你撤销。这正是「不依赖任何人」的另一面。\n\n对做生意的人，我的实话是：**生意的钱不是风险钱。** 下个月要付供应商、房租和工资的钱，不能放在下个月可能只值一半的东西里。如果你有兴趣，用那种全亏掉也不影响生活的个人闲钱去做——并且对任何承诺「固定收益」的人保持警惕，因为那已经不是加密货币，是换了个新名字的老骗局。",
    },
  },
  {
    id: "jubilacion_retiro",
    titulo: { es: "El retiro cuando trabajas por tu cuenta", en: "Retirement when you're self-employed", pt: "Aposentadoria trabalhando por conta própria", fr: "La retraite à son compte", de: "Rente als Selbstständige", it: "La pensione quando lavori in proprio", zh: "自己做生意的人如何养老" },
    relacionados: ["fondo_emergencia", "separar_finanzas", "cuadrante_flujo"],
    palabras: ["retiro", "jubilacion", "pension", "afore", "cuando me retire", "vejez", "para cuando sea viejo", "retirement", "pension", "aposentadoria", "retraite", "rente", "pensione", "退休", "养老"],
    respuesta: {
      es: "El problema de tener un negocio propio es que **nadie te está ahorrando el retiro por detrás.** Un empleado tiene descuentos automáticos; tú tienes lo que decidas apartar tú mismo, y no hay nadie que te lo recuerde.\n\nTres cosas que cambian mucho el resultado:\n\n• **Empezar temprano vale más que aportar mucho.** Por el interés compuesto, lo que apartas a los 30 puede pesar más que el doble apartado a los 45. El tiempo hace más trabajo que la cantidad.\n• **Tu negocio no es tu plan de retiro.** Mucha gente asume que va a vender el negocio y con eso vivir. La mayoría de los negocios chicos no se venden, o se venden en mucho menos de lo que su dueño imaginaba, porque el negocio *es* el dueño: sin él no queda nada que comprar.\n• **Aporta aunque sea poco, pero fijo.** Una cantidad chica todos los meses le gana a una cantidad grande cuando \"sobre\", porque nunca sobra.\n\nEn México puedes aportar voluntariamente a tu Afore aunque seas independiente, y esas aportaciones tienen ventajas fiscales. En otros países hay figuras equivalentes. Cuál te conviene depende de tu ingreso y tu régimen — vale la pena preguntarlo una vez con alguien que sepa, y luego automatizarlo y olvidarte.",
      en: "The problem with running your own business is that **nobody is saving for your retirement in the background.** An employee has automatic deductions; you have whatever you decide to set aside yourself, and nobody reminds you.\n\nThree things that change the outcome most:\n\n• **Starting early beats contributing a lot.** Thanks to compounding, what you set aside at 30 can outweigh twice as much set aside at 45. Time does more work than the amount.\n• **Your business is not your retirement plan.** Many people assume they'll sell the business and live off it. Most small businesses don't sell, or sell for far less than the owner imagined, because the business *is* the owner: without them there's nothing left to buy.\n• **Contribute small but fixed.** A small amount every month beats a big amount \"when there's spare\", because there never is.\n\nIn Mexico you can pay voluntarily into your Afore even as a freelancer, and those contributions carry tax advantages. Other countries have equivalents. Which suits you depends on your income and tax regime — worth asking someone who knows, once, then automating it and forgetting about it.",
      pt: "O problema de ter negócio próprio é que **ninguém está poupando sua aposentadoria por trás.** Um empregado tem descontos automáticos; você tem o que decidir separar, e não há quem lembre.\n\nTrês coisas que mudam muito o resultado:\n\n• **Começar cedo vale mais que aportar muito.** Pelos juros compostos, o que você separa aos 30 pode pesar mais que o dobro separado aos 45. O tempo trabalha mais que o valor.\n• **Seu negócio não é seu plano de aposentadoria.** Muita gente assume que vai vender o negócio e viver disso. A maioria dos negócios pequenos não vende, ou vende por muito menos do que o dono imaginava, porque o negócio *é* o dono: sem ele não sobra nada para comprar.\n• **Aporte pouco, mas fixo.** Um valor pequeno todo mês ganha de um valor grande \"quando sobrar\", porque nunca sobra.\n\nAs figuras disponíveis mudam por país e o que te convém depende da sua renda e do seu regime — vale perguntar uma vez a quem entende, automatizar e esquecer.",
      fr: "Le problème quand on a son affaire, c'est que **personne n'épargne votre retraite en coulisses.** Un salarié a des prélèvements automatiques ; vous avez ce que vous décidez de mettre de côté, et personne ne vous le rappelle.\n\nTrois choses qui changent le résultat :\n\n• **Commencer tôt vaut mieux que cotiser beaucoup.** Grâce aux intérêts composés, ce que vous mettez de côté à 30 ans peut peser plus que le double à 45 ans. Le temps travaille plus que le montant.\n• **Votre entreprise n'est pas votre plan de retraite.** Beaucoup pensent la revendre et en vivre. La plupart des petites entreprises ne se vendent pas, ou bien moins cher qu'imaginé, parce que l'entreprise *c'est* le patron : sans lui, il ne reste rien à acheter.\n• **Cotisez peu, mais régulièrement.** Un petit montant chaque mois bat un gros montant « quand il en restera », car il n'en reste jamais.\n\nLes dispositifs varient selon le pays et ce qui vous convient dépend de vos revenus et de votre régime — cela vaut la peine de demander une fois à quelqu'un qui s'y connaît, puis d'automatiser et d'oublier.",
      de: "Das Problem am eigenen Betrieb ist, dass **niemand im Hintergrund für deine Rente spart.** Angestellte haben automatische Abzüge; du hast das, was du selbst zurücklegst, und niemand erinnert dich daran.\n\nDrei Dinge, die das Ergebnis am stärksten verändern:\n\n• **Früh anfangen schlägt viel einzahlen.** Durch den Zinseszins kann das, was du mit 30 zurücklegst, mehr wiegen als das Doppelte mit 45. Die Zeit arbeitet mehr als der Betrag.\n• **Dein Betrieb ist nicht deine Altersvorsorge.** Viele nehmen an, sie verkaufen den Betrieb und leben davon. Die meisten kleinen Betriebe lassen sich nicht verkaufen oder nur für viel weniger als gedacht, weil der Betrieb *die Inhaberin oder der Inhaber ist*: Ohne sie bleibt nichts zu kaufen.\n• **Zahl lieber wenig, aber fest ein.** Ein kleiner Betrag jeden Monat schlägt einen großen „wenn was übrig ist\", denn es bleibt nie etwas übrig.\n\nDie Möglichkeiten unterscheiden sich je nach Land, und was zu dir passt, hängt von Einkommen und Besteuerung ab — einmal jemanden fragen, der sich auskennt, dann automatisieren und vergessen.",
      it: "Il problema di avere un'attività propria è che **nessuno sta accantonando la tua pensione dietro le quinte.** Un dipendente ha trattenute automatiche; tu hai quello che decidi di mettere da parte, e nessuno te lo ricorda.\n\nTre cose che cambiano di più il risultato:\n\n• **Iniziare presto vale più che versare tanto.** Per l'interesse composto, quello che accantoni a 30 anni può pesare più del doppio accantonato a 45. Il tempo lavora più dell'importo.\n• **La tua attività non è il tuo piano pensione.** Molti danno per scontato di vendere l'attività e viverci. La maggior parte delle piccole attività non si vende, o si vende a molto meno di quanto il titolare immaginava, perché l'attività *è* il titolare: senza di lui non resta nulla da comprare.\n• **Versa poco, ma fisso.** Una cifra piccola ogni mese batte una grande \"quando avanza\", perché non avanza mai.\n\nGli strumenti cambiano per paese e quello che ti conviene dipende dal reddito e dal regime — vale la pena chiedere una volta a chi se ne intende, poi automatizzare e dimenticarsene.",
      zh: "自己做生意的问题在于：**没有人在背后替你攒养老钱。** 上班族有自动扣缴；你只有自己决定留出来的那部分，而且没人提醒你。\n\n三件对结果影响最大的事：\n\n• **早开始比多投更重要。** 因为复利，30 岁存下的钱，可能比 45 岁存双倍还管用。时间干的活比金额多。\n• **你的生意不是你的养老计划。** 很多人默认「到时候把店卖了就够养老」。多数小生意卖不掉，或者卖的价远低于老板的想象——因为这门生意*就是*老板本人：人一走，就没什么可买的了。\n• **金额小没关系，要固定。** 每月一小笔，胜过「有余钱时」的一大笔，因为永远没有余钱。\n\n在墨西哥，即使是个体经营也可以自愿向 Afore 补充缴存，而且有税收优惠。其他国家有对应的制度。哪种适合你，取决于收入和纳税方式——值得找懂行的人问一次，然后设成自动扣款，忘掉它。",
    },
  },
];
